# IED Subset

This is the first notebook in the series used to prepare the Irish Emigration Database subset for analysis. The goals of this series are:
<ol>
    <li>To identify the existing data structure;</li>
    <li>To identify how it must be restructured to match the data structure of the Naildoh subset;</li>
    <li>To make the necessary changes;</li>
    <li>To merge the two dataframes.</li>
 </ol>

## Resources

In [2]:
# Libraries
library(tidyverse) # for data manipulation

In [3]:
# Functions
factorize <- function(df){ # Create a function
  for(i in which(sapply(df, class) == "character")) # that looks for variables with the character class 
      df[[i]] = as.factor(df[[i]]) # and converts them to factor (i.e., categorical) class
  return(df)
}

unfactorize <- function(df){ # Create a function
  for(i in which(sapply(df, class) == "factor")) # that looks for variables with the character class 
      df[[i]] = as.character(df[[i]]) # and converts them to factor (i.e., categorical) class
  return(df)
}

In [4]:
# Data
df <- factorize(read.csv("20230514_AM_ied.csv", header=FALSE, sep=",")) # Put csv into a dataframe called docData

# Variabe Names
colnames(df)
dim(df)
df[0:1,]


[1] "V1" "V2" "V3" "V4" "V5" "V6"

[1] 3055    6

V1     V2         V3                  V4                                    
1 300090 04-12-1896 Letters (Emigrants) Public Record Office, Northern Ireland
  V5                                                                                  
1 Edward Stanley, Katawa, Canada to Joshua Peel, Armagh; PRONI D889/7/1; CMSIED 300090
  V6   
1 20481

In [5]:
colnames(df) <- c('idIED', 
                       'ddmmyyyy', 
                       'publisher', 
                       'sourcetitle', 
                       'description', 
                       'docid')
df[0:1,]

idIED  ddmmyyyy   publisher           sourcetitle                           
1 300090 04-12-1896 Letters (Emigrants) Public Record Office, Northern Ireland
  description                                                                         
1 Edward Stanley, Katawa, Canada to Joshua Peel, Armagh; PRONI D889/7/1; CMSIED 300090
  docid
1 20481

In [7]:
main <- read.csv("20240510_PhD_NaildohSubset.csv")
colnames(main) # Get an overview of the dataframe
dim(main)
main[0:1,]

[1] "docauthorid"    "docauthorname"  "docid"          "docyear"       
 [5] "docmonth"       "authorgender"   "agewriting"     "agedeath"      
 [9] "religionNew"    "relMin"         "nationalOrigin" "authorLocation"
[13] "A"              "I"              "CCP"            "UWL"           
[17] "U"              "M"              "S"              "F"             
[21] "L"

[1] 492  21

docauthorid docauthorname                      docid      docyear docmonth
1 per0001043  Segale, Sister Blandina, 1850-1941 S1019-D002 1872    11      
  authorgender agewriting agedeath religionNew relMin ⋯ authorLocation A    
1 F            22         91       Catholic    TRUE   ⋯ USA            FALSE
  I     CCP  UWL   U    M    S     F     L    
1 FALSE TRUE FALSE TRUE TRUE FALSE FALSE FALSE

First to main df, add "publisher" (NAILDOH).

Then for df, keep docid as it is, and make the following adjustments:

<ul>
    <li>docauthorid (create from docauthorname)</li>
    <li>docauthorname (description)</li>
    <li>docyear (mm-dd-yyyy)</li>
    <li>docmonth (mm-dd-yyyy)</li>
   <li>authorgender (NA)</li>
    <li>agewriting (NA)</li>
    <li>agedeath (NA)</li>
    <li>relMin (NA)</li>
    <li>nationalOrigin ("Ireland")</li>
    <li>authorLocation (description)</li>
    <li>U (NA)</li>
    <li>M (NA)</li>
    <li>S (NA)</li>
    <li>F (NA)</li>
    <li>L (NA)</li>
 </ul>
  


In [8]:
# Change to main:
main$publisher <- "NAILDOH"
main

docauthorid
1   per0001043 
2   per0001043 
3   per0001043 
4   per0001043 
5   per0001043 
6   per0001043 
7   per0001043 
8   per0001043 
9   per0001043 
10  per0001043 
11  per0001043 
12  per0001043 
13  per0001043 
14  per0001043 
15  per0001043 
16  per0001043 
17  per0001043 
18  per0001043 
19  per0001043 
20  per0001043 
21  per0001043 
22  per0001043 
23  per0001043 
24  per0001043 
25  per0001043 
26  per0001043 
27  per0001043 
28  per0001043 
29  per0001043 
30  per0001043 
⋮   ⋮          
463 per0036382 
464 per0036382 
465 per0036383 
466 per0036380 
467 per0036385 
468 per0036387 
469 per0029301 
470 per0038828 
471 per0038828 
472 per0038844 
473 per0038859 
474 per0038862 
475 per0038979 
476 per0038980 
477 per0038989 
478 per0022728 
479 per0034430 
480 per0034430 
481 per0034430 
482 per0035059 
483 per0035059 
484 per0022766 
485 per0022766 
486 per0022766 
487 per0022894 
488 per0022894 
489 per0022894 
490 per0022894 
491 per0036192 
492 per0036196 
    docauthorname                                                                  
1   Segale, Sister Blandina, 1850-1941                                             
2   Segale, Sister Blandina, 1850-1941                                             
3   Segale, Sister Blandina, 1850-1941                                             
4   Segale, Sister Blandina, 1850-1941                                             
5   Segale, Sister Blandina, 1850-1941                                             
6   Segale, Sister Blandina, 1850-1941                                             
7   Segale, Sister Blandina, 1850-1941                                             
8   Segale, Sister Blandina, 1850-1941                                             
9   Segale, Sister Blandina, 1850-1941                                             
10  Segale, Sister Blandina, 1850-1941                                             
11  Segale, Sister Blandina, 1850-1941                                             
12  Segale, Sister Blandina, 1850-1941                                             
13  Segale, Sister Blandina, 1850-1941                                             
14  Segale, Sister Blandina, 1850-1941                                             
15  Segale, Sister Blandina, 1850-1941                                             
16  Segale, Sister Blandina, 1850-1941                                             
17  Segale, Sister Blandina, 1850-1941                                             
18  Segale, Sister Blandina, 1850-1941                                             
19  Segale, Sister Blandina, 1850-1941                                             
20  Segale, Sister Blandina, 1850-1941                                             
21  Segale, Sister Blandina, 1850-1941                                             
22  Segale, Sister Blandina, 1850-1941                                             
23  Segale, Sister Blandina, 1850-1941                                             
24  Segale, Sister Blandina, 1850-1941                                             
25  Segale, Sister Blandina, 1850-1941                                             
26  Segale, Sister Blandina, 1850-1941                                             
27  Segale, Sister Blandina, 1850-1941                                             
28  Segale, Sister Blandina, 1850-1941                                             
29  Segale, Sister Blandina, 1850-1941                                             
30  Segale, Sister Blandina, 1850-1941                                             
⋮   ⋮                                                                              
463 Anonymous Young Scotsman on the Trent River, Canada, fl. 1833                  
464 Anonymous Young Scotsman on the Trent River, Canada, fl. 1833                  
465 Anonymous Young Scottish Immigrant in Montreal, fl. 1833                       
466 Anonymous Young Scottish Male Immigrant at Whitby, Canada, fl. 1833 

In [9]:
# Data
statesUSA <- factorize(read.csv("20240429_PhD_StatesUSA.csv", header=TRUE, sep=",")) # Put csv into a dataframe called docData
glimpse(statesUSA)

Rows: 51
Columns: 2
$ State        <fct> Alabama, Alaska, Arizona, Arkansas, California, Colorado,…
$ Abbreviation <fct> AL, AK, AZ, AR, CA, CO, CT, DE, DC, FL, GA, HI, ID, IL, I…


In [10]:
# Data
namesFemale <- factorize(read.table("female.txt", header=FALSE)) # Put csv into a dataframe called docData
glimpse(namesFemale)

Rows: 5,004
Columns: 1
$ V1 <fct> Abagael, Abagail, Abbe, Abbey, Abbi, Abbie, Abby, Abigael, Abigail,…


In [11]:
# Data
namesMale <- factorize(read.table("male.txt", header=FALSE)) # Put csv into a dataframe called docData
glimpse(namesMale)

Rows: 2,943
Columns: 1
$ V1 <fct> Aamir, Aaron, Abbey, Abbie, Abbot, Abbott, Abby, Abdel, Abdul, Abdu…


## Changes

In [12]:
# First the easy changes to df
df$publisher <- "IED"
df$nationalOrigin <- "Irish"
df

idIED     ddmmyyyy   publisher sourcetitle                           
1     300090   04-12-1896 IED       Public Record Office, Northern Ireland
2    9501251   12-01-1891 IED       Public Record Office, Northern Ireland
3     300018   01-06-1822 IED       Ulster-American Folk Park.            
4    9408355   01-10-1842 IED       Public Record Office, Northern Ireland
5    9003061   10-01-1896 IED       Public Record Office, Northern Ireland
6    9011027   13-02-1873 IED       Public Record Office, Northern Ireland
7    9905110   16-05-1891 IED       Ulster-American Folk Park.            
8    9006021   01-01-1862 IED       Public Record Office, Northern Ireland
9    9411034   15-02-1858 IED       Public Record Office, Northern Ireland
10   8906036   08-09-1886 IED       Public Record Office, Northern Ireland
11   9808492   29-03-1808 IED       Public Record Office, Northern Ireland
12   8905199   01-01-1800 IED       Public Record Office, Northern Ireland
13   9902174   06-08-1891 IED       B. O'Reilly                           
14   9004027   22-09-1870 IED       Public Record Office, Northern Ireland
15   9502061   08-03-1859 IED       Public Record Office, Northern Ireland
16   9504036   04-07-1834 IED       Public Record Office, Northern Ireland
17   9309131   18-03-1866 IED       Public Record Office, Northern Ireland
18   9407001   17-11-1874 IED       Public Record Office, Northern Ireland
19   9906113   26-06-1890 IED       Ulster-American Folk Park.            
20   1200298   09-04-1901 IED       Public Record Office, Northern Ireland
21   9002017   08-06-1851 IED       Public Record Office, Northern Ireland
22   9906120   05-07-1890 IED       Ulster-American Folk Park.            
23   8901021   10-10-1802 IED       Public Record Office, Northern Ireland
24   9501040   03-01-1867 IED       Public Record Office, Northern Ireland
25   2006172   31-03-1837 IED       Public Record Office, Northern Ireland
26   9410220   07-08-1842 IED       Public Record Office, Northern Ireland
27   9601085   14-01-1866 IED       Public Record Office, Northern Ireland
28    111060   18-01-1897 IED       Mellon Centre for Migration Studies   
29   9705005   05-12-1892 IED       Public Record Office, Northern Ireland
30   9007034   23-06-1901 IED       Public Record Office, Northern Ireland
⋮    ⋮         ⋮          ⋮         ⋮                                     
3026   9503126 28-09-1857 IED       Public Record Office, Northern Ireland
3027    701100 13-11-1841 IED       Mellon Centre for Migration Studies   
3028   8905207 16-11-1832 IED       Public Record Office, Northern Ireland
3029    100002 18-08-1852 IED       Linenhall Library                     
3030   9006111 24-11-1814 IED       Public Record Office, Northern Ireland
3031   8810006 07-07-1860 IED       Public Record Office, Northern Ireland
3032   8809224 10-07-1820 IED       Public Record Office, Northern Ireland
3033   9810041 08-01-1899 IED       Public Record Office, Northern Ireland
3034   9501108 16-01-1873 IED       Public Record Office, Northern Ireland
3035   9311532 01-02-1842 IED       Public Record Office, Northern Ireland
3036   9502178 01-01-1870 IED       Public Record Office, Northern Ireland
3037   9408092 19-12-1879 IED       Public Record Office, Northern Ireland
3038   8950004 10-05-1838 IED       Public Record Office, Northern Ireland
3039   9906065 28-05-1891 IED       Ulster-American Folk Park.            
3040   9806863 30-09-1913 IED       B. O'Reilly                           
3041   9904201 09-01-1886 IED       Ulster-American Folk Park.            
3042   9006023 14-12-1868 IED       Public Record Office, Northern Ireland
3043   9409347 05-04-1865 IED       Public Record Office, Northern Ireland
3044   9702157 13-10-1847 IED       Ulster-American Folk Park.            
3045   9705006 01-01-1892 IED       Public Record Office, Northern Ireland
3046    201116 05-03-1855 IED       Public Record Office, Northern Ireland
3047   9007147 18-06-1854 IED 

In [13]:
vars <- c("authorgender", "agewriting", "agedeath", "relMin", "U", "M", "S", "F", "L")
df[vars] <- NA
df

idIED     ddmmyyyy   publisher sourcetitle                           
1     300090   04-12-1896 IED       Public Record Office, Northern Ireland
2    9501251   12-01-1891 IED       Public Record Office, Northern Ireland
3     300018   01-06-1822 IED       Ulster-American Folk Park.            
4    9408355   01-10-1842 IED       Public Record Office, Northern Ireland
5    9003061   10-01-1896 IED       Public Record Office, Northern Ireland
6    9011027   13-02-1873 IED       Public Record Office, Northern Ireland
7    9905110   16-05-1891 IED       Ulster-American Folk Park.            
8    9006021   01-01-1862 IED       Public Record Office, Northern Ireland
9    9411034   15-02-1858 IED       Public Record Office, Northern Ireland
10   8906036   08-09-1886 IED       Public Record Office, Northern Ireland
11   9808492   29-03-1808 IED       Public Record Office, Northern Ireland
12   8905199   01-01-1800 IED       Public Record Office, Northern Ireland
13   9902174   06-08-1891 IED       B. O'Reilly                           
14   9004027   22-09-1870 IED       Public Record Office, Northern Ireland
15   9502061   08-03-1859 IED       Public Record Office, Northern Ireland
16   9504036   04-07-1834 IED       Public Record Office, Northern Ireland
17   9309131   18-03-1866 IED       Public Record Office, Northern Ireland
18   9407001   17-11-1874 IED       Public Record Office, Northern Ireland
19   9906113   26-06-1890 IED       Ulster-American Folk Park.            
20   1200298   09-04-1901 IED       Public Record Office, Northern Ireland
21   9002017   08-06-1851 IED       Public Record Office, Northern Ireland
22   9906120   05-07-1890 IED       Ulster-American Folk Park.            
23   8901021   10-10-1802 IED       Public Record Office, Northern Ireland
24   9501040   03-01-1867 IED       Public Record Office, Northern Ireland
25   2006172   31-03-1837 IED       Public Record Office, Northern Ireland
26   9410220   07-08-1842 IED       Public Record Office, Northern Ireland
27   9601085   14-01-1866 IED       Public Record Office, Northern Ireland
28    111060   18-01-1897 IED       Mellon Centre for Migration Studies   
29   9705005   05-12-1892 IED       Public Record Office, Northern Ireland
30   9007034   23-06-1901 IED       Public Record Office, Northern Ireland
⋮    ⋮         ⋮          ⋮         ⋮                                     
3026   9503126 28-09-1857 IED       Public Record Office, Northern Ireland
3027    701100 13-11-1841 IED       Mellon Centre for Migration Studies   
3028   8905207 16-11-1832 IED       Public Record Office, Northern Ireland
3029    100002 18-08-1852 IED       Linenhall Library                     
3030   9006111 24-11-1814 IED       Public Record Office, Northern Ireland
3031   8810006 07-07-1860 IED       Public Record Office, Northern Ireland
3032   8809224 10-07-1820 IED       Public Record Office, Northern Ireland
3033   9810041 08-01-1899 IED       Public Record Office, Northern Ireland
3034   9501108 16-01-1873 IED       Public Record Office, Northern Ireland
3035   9311532 01-02-1842 IED       Public Record Office, Northern Ireland
3036   9502178 01-01-1870 IED       Public Record Office, Northern Ireland
3037   9408092 19-12-1879 IED       Public Record Office, Northern Ireland
3038   8950004 10-05-1838 IED       Public Record Office, Northern Ireland
3039   9906065 28-05-1891 IED       Ulster-American Folk Park.            
3040   9806863 30-09-1913 IED       B. O'Reilly                           
3041   9904201 09-01-1886 IED       Ulster-American Folk Park.            
3042   9006023 14-12-1868 IED       Public Record Office, Northern Ireland
3043   9409347 05-04-1865 IED       Public Record Office, Northern Ireland
3044   9702157 13-10-1847 IED       Ulster-American Folk Park.            
3045   9705006 01-01-1892 IED       Public Record Office, Northern Ireland
3046    201116 05-03-1855 IED       Public Record Office, Northern Ireland
3047   9007147 18-06-1854 IED 

In [14]:
# Now the tougher ones. First break out date into month, year and day.
df$ddmmyyyy <- as.character(df$ddmmyyyy)
str(df$ddmmyyyy)

 chr [1:3055] "04-12-1896" "12-01-1891" "01-06-1822" "01-10-1842" ...


In [16]:
# Now new ones based on old ones
# Dates
df$docmonth <- as.factor(str_sub(df$ddmmyyyy, 4, 5))
df$docyear <- as.numeric(str_sub(df$ddmmyyyy, -4,-1))
vars <- c("docmonth", "docyear")
df[vars] %>% 
summary()

    docmonth       docyear    
 01     : 376   Min.   :1750  
 12     : 291   1st Qu.:1844  
 11     : 276   Median :1865  
 06     : 262   Mean   :1860  
 09     : 250   3rd Qu.:1888  
 03     : 243   Max.   :1913  
 (Other):1357                 

In [17]:
#Names
unique(df$description)[0:50]

[1] Edward Stanley, Katawa, Canada to Joshua Peel, Armagh; PRONI D889/7/1; CMSIED 300090                                                                
 [2] From, Brooklyn, N.Y., to "Dear James" [no address]; PRONI T 3033/10; CMSIED 9501251                                                                 
 [3] James Kelly, Desertmartin to John Kelly, Pennsylvania;The Kelly Family Documents: Copyright Retained by The UlsterAmerican Folk Park.; CMSIED 300018
 [4] Alexander McCloy, Pennsylvania, to Cousin, [Ireland? or Liverpool, England?]; PRONI D1444/18; CMSIED 9408355                                        
 [5] George Kirkpatrick, Toronto, to Rev. Alex. Kirkpatrick, Co Antrim; PRONI D 1424/11; CMSIED 9003061                                                  
 [6] William Porter, U.S.A. to Robert Porter, Ireland; PRONI D 1152/3/25; CMSIED 9011027                                                                 
 [7] G.R. Wood, Holly, Michigan to Annie Weir, Michigan;Copyright Retained by Mrs. Linda Weir; CMSIED 9905110                                            
 [8] Alexander Robb, Near Panama, to Family [Dundonald, Co Down?]; PRONI T 1454/6/2; CMSIED 9006021                                                      
 [9] N. Carrothers, Ontario to W.Carrothers, Farnaght, Fermanagh; PRONI T3734; CMSIED 9411034                                                            
[10] James P. Breeze, Concord, to Charley Breeze.; PRONI T 1381/9; CMSIED 8906036                                                                        
[11] Elisha & Lois Parish, U.S.A. to Moses Johnston, New York.; PRONI T 3758/8; CMSIED 9808492                                                           
[12] Robert McClorg [Philadelphia?] to Parents, Co Londonderry.; PRONI T.1227/33; CMSIED 8905199                                                         
[13] O Bouligny, [New Orleans?] To [Mrs A. W. Smyth?] [Massachusetts?].;Brendan O'Reilly.; CMSIED 9902174                                                
[14] [?], Kingston, Canada, to George [Kirkpatrick, Co Antrim?]; PRONI D 1424/11; CMSIED 9004027                                                         
[15] Martha Wilson, Ontario, to her Brother, George Reid, Armagh.; PRONI D3014/3/2; CMSIED 9502061                                                       
[16] James Heather, Montreal, Canada, to Thomas Greeves, Dungannon.; PRONI D 593/5; CMSIED 9504036                                                       
[17] Richard Rothwell, Jeffersonville, to rosa Rothwell, Ireland, Mar. 1866; PRONI T2621/3/10; CMSIED 9309131                                            
[18] Kate Brown, Canada, to her Aunt Catherine Kirkpatrick, Co Antrim; PRONI D1604/270; CMSIED 9407001                                                   
[19] A. Jackson, Southfield, To Annie Weir, [?];Copyright Retained By Mrs Linda Weir; CMSIED 9906113                                                     
[20] Mary Dwyer, Independence, Iowa, to "Rev. Father", Co. Armagh.; PRONI D889/7/1; CMSIED 1200298                                                       
[21] Edward McNally, USA  to William McNally, Portaferry.; PRONI T 1448; CMSIED 9002017                                                                  
[22] E. Megaw, [?], to [Annie Weir?] [?];Copyright Retained By Mrs Linda Weir; CMSIED 9906120                                                            
[23] James Horner, Philadelphia to Jacob McCracken, Co. Derry.; PRONI T 1592/10; CMSIED 8901021                                                          
[24] Samuel Shaw, Chicago, Illinois, U.S.A., to His Mother, [Co. Down?]; PRONI D2709/1/4; CMSIED 9501040                                                 
[25] William Smith, Philadelphia to James Smyth, Co. Antrim; PRONI D 1828/4; CMSIED 2006172                                                              
[26] James Ormond, New York, informant to Viscount Canterbury, Mildenhall; PRONI T3069/; CMSIED 9410220                                                

For this variable, I am concerned with the sender names, not the locations or recipients, so I am going to drop everything after the first comma.

In [18]:
df$docauthorname <- gsub(",.*\\b", "", df$description)
unique(df$docauthorname)[0:50]

[1] "Edward Stanley"                                                                       
 [2] "From"                                                                                 
 [3] "James Kelly"                                                                          
 [4] "Alexander McCloy"                                                                     
 [5] "George Kirkpatrick"                                                                   
 [6] "William Porter"                                                                       
 [7] "G.R. Wood"                                                                            
 [8] "Alexander Robb"                                                                       
 [9] "N. Carrothers"                                                                        
[10] "James P. Breeze"                                                                      
[11] "Elisha & Lois Parish"                                                                 
[12] "Robert McClorg [Philadelphia?] to Parents"                                            
[13] "O Bouligny"                                                                           
[14] "[?]"                                                                                  
[15] "Martha Wilson"                                                                        
[16] "James Heather"                                                                        
[17] "Richard Rothwell"                                                                     
[18] "Kate Brown"                                                                           
[19] "A. Jackson"                                                                           
[20] "Mary Dwyer"                                                                           
[21] "Edward McNally"                                                                       
[22] "E. Megaw"                                                                             
[23] "James Horner"                                                                         
[24] "Samuel Shaw"                                                                          
[25] "William Smith"                                                                        
[26] "James Ormond"                                                                         
[27] "A. Aitken"                                                                            
[28] "Jim Swan"                                                                             
[29] "Philip Formby"                                                                        
[30] "Samuel James McCreery"                                                                
[31] "William W Shaw"                                                                       
[32] "Wm. Heather"                                                                          
[33] "William Parke"                                                                        
[34] "Alex McLeod"                                                                          
[35] "Isabella Weir"                                                                        
[36] "Leydd McCrory [?]"                                                                    
[37] "William W. Shaw"                                                                      
[38] "John Parks to John Caldwell Junior; PRONI T 3541/2/2; CMSIED 9309353"                 
[39] "I. Pemberton"                                                                         
[40] "William Montgomery"                                                                   
[41] "[?] Sample"                                                                           
[42] "Hamilton Young"                                                                       
[43] "James and Margaret Carson"                                                            
[4

Now I am dropping everything after "to" in those cases where it appears.

In [19]:
df$docauthorname <- gsub(".to.*","", df$docauthorname)
unique(df$docauthorname)[0:50]

[1] "Edward Stanley"                                                                       
 [2] "From"                                                                                 
 [3] "James Kelly"                                                                          
 [4] "Alexander McCloy"                                                                     
 [5] "George Kirkpatrick"                                                                   
 [6] "William Porter"                                                                       
 [7] "G.R. Wood"                                                                            
 [8] "Alexander Robb"                                                                       
 [9] "N. Carrothers"                                                                        
[10] "James P. Breeze"                                                                      
[11] "Elisha & Lois Parish"                                                                 
[12] "Robert McClorg [Philadelphia?]"                                                       
[13] "O Bouligny"                                                                           
[14] "[?]"                                                                                  
[15] "Martha Wilson"                                                                        
[16] "James Heather"                                                                        
[17] "Richard Rothwell"                                                                     
[18] "Kate Brown"                                                                           
[19] "A. Jackson"                                                                           
[20] "Mary Dwyer"                                                                           
[21] "Edward McNally"                                                                       
[22] "E. Megaw"                                                                             
[23] "James Horner"                                                                         
[24] "Samuel Shaw"                                                                          
[25] "William Smith"                                                                        
[26] "James Ormond"                                                                         
[27] "A. Aitken"                                                                            
[28] "Jim Swan"                                                                             
[29] "Philip Formby"                                                                        
[30] "Samuel James McCreery"                                                                
[31] "William W Shaw"                                                                       
[32] "Wm. Heather"                                                                          
[33] "William Parke"                                                                        
[34] "Alex McLeod"                                                                          
[35] "Isabella Weir"                                                                        
[36] "Leydd McCrory [?]"                                                                    
[37] "William W. Shaw"                                                                      
[38] "John Parks"                                                                           
[39] "I. Pembe"                                                                             
[40] "William Montgomery"                                                                   
[41] "[?] Sample"                                                                           
[42] "Hami"                                                                                 
[43] "James and Margaret Carson"                                                            
[4

In [20]:
# Cleaning up a few more problems.
df$docauthorname <- gsub("From", "", df$docauthorname)# From
df$docauthorname <- gsub("\\[.*\\]","", df$docauthorname) #Brackets and contents thereof
df$docauthorname <- gsub("\\;.*","", df$docauthorname) #Everything after semi-colon
df$docauthorname <- gsub(".for.*","", df$docauthorname) #Everything after "for"
unique(df$docauthorname)[0:50]

[1] "Edward Stanley"                     ""                                  
 [3] "James Kelly"                        "Alexander McCloy"                  
 [5] "George Kirkpatrick"                 "William Porter"                    
 [7] "G.R. Wood"                          "Alexander Robb"                    
 [9] "N. Carrothers"                      "James P. Breeze"                   
[11] "Elisha & Lois Parish"               "Robert McClorg "                   
[13] "O Bouligny"                         "Martha Wilson"                     
[15] "James Heather"                      "Richard Rothwell"                  
[17] "Kate Brown"                         "A. Jackson"                        
[19] "Mary Dwyer"                         "Edward McNally"                    
[21] "E. Megaw"                           "James Horner"                      
[23] "Samuel Shaw"                        "William Smith"                     
[25] "James Ormond"                       "A. Aitken"                         
[27] "Jim Swan"                           "Philip Formby"                     
[29] "Samuel James McCreery"              "William W Shaw"                    
[31] "Wm. Heather"                        "William Parke"                     
[33] "Alex McLeod"                        "Isabella Weir"                     
[35] "Leydd McCrory "                     "William W. Shaw"                   
[37] "John Parks"                         "I. Pembe"                          
[39] "William Montgomery"                 " Sample"                           
[41] "Hami"                               "James and Margaret Carson"         
[43] "Thomas Armstrong"                   "Solomon Moody"                     
[45] "Reference written by James Barbour" "Andrew Gibson"                     
[47] "E. Rothwell"                        "John McBride"                      
[49] "George Doyle"                       "E. Cochrane"

References letters are ok but we don't need this in the author variable.

In [21]:
df$docauthorname <- gsub("Reference written by ","", df$docauthorname)
unique(df$docauthorname)[0:50]

[1] "Edward Stanley"            ""                         
 [3] "James Kelly"               "Alexander McCloy"         
 [5] "George Kirkpatrick"        "William Porter"           
 [7] "G.R. Wood"                 "Alexander Robb"           
 [9] "N. Carrothers"             "James P. Breeze"          
[11] "Elisha & Lois Parish"      "Robert McClorg "          
[13] "O Bouligny"                "Martha Wilson"            
[15] "James Heather"             "Richard Rothwell"         
[17] "Kate Brown"                "A. Jackson"               
[19] "Mary Dwyer"                "Edward McNally"           
[21] "E. Megaw"                  "James Horner"             
[23] "Samuel Shaw"               "William Smith"            
[25] "James Ormond"              "A. Aitken"                
[27] "Jim Swan"                  "Philip Formby"            
[29] "Samuel James McCreery"     "William W Shaw"           
[31] "Wm. Heather"               "William Parke"            
[33] "Alex McLeod"               "Isabella Weir"            
[35] "Leydd McCrory "            "William W. Shaw"          
[37] "John Parks"                "I. Pembe"                 
[39] "William Montgomery"        " Sample"                  
[41] "Hami"                      "James and Margaret Carson"
[43] "Thomas Armstrong"          "Solomon Moody"            
[45] "James Barbour"             "Andrew Gibson"            
[47] "E. Rothwell"               "John McBride"             
[49] "George Doyle"              "E. Cochrane"

Now, what is this sample?

In [22]:
df %>% 
filter(docauthorname==" Sample") %>% 
select(docid)

docid
1 20976

In [23]:
getwd()

[1] "/Users/alaynemoody/Dropbox/GradStudies/Flinders/Dissertation"

In [26]:
read_file(paste0("/Users/alaynemoody/Dropbox/GradStudies/Flinders/Dissertation/IED/", "20976.txt"))

[1] "                137 North Elliott Place\n                Brooklyn N. [New?] York\n                                  U.S.A\n                         April 5th 1897\n\nMrs Ellen McIntire [McIntyre?]\n                My dear sister\n                            Your\nkind letter gave us sincere\ncomfort. I know that James\nwas very negligent about\nwriting to you. I often asked\nhim why he did not write to\nhis sisters and all he would\nsay was \"I dont know\". I believe\nthat he felt discouraged\nand chagrined at his failure\nof success in his business life\nand did not like to own it\nto his relatives. You say that\nyou heard the boys took\nadvantage of their Father He\nalways blamed them a great\ndeal perhaps too much but\nthey were never any great\nhelp to him and When\nbusiness was very dull and\ntimes hard and his health\nvery poor they left him to\nstruggle on alone and he\nhad to give up. I only\nblame one of them (Joseph)\nand I am having hard\ntrouble with him now to\nget some money he was\nowing his father. Samuel was\na great trial as he was given\nto drink. He died three years\nago. \"James Lalta\" has two children\nand lives in another county\nabout two hours travel\nJoseph is married, no children\nin dry goods business here\nin Brooklyn.\n\"Charles Walker\" is married one\nchild - dry goods - here in\nBrooklyn. All friendly\nexcept Joseph and he\nis not friendly with his brothers\n#PAGE 2\n   And now you will think\nthat I have been unmindful\nof you [your?] request to have one\narticle written. I have been\ndoing my best but it has\nbeen slow work. In the first\nplace I scarcely knew who\nto ask to write it as we\nhave had several different\n pastors in the last 12 years\nand all but the last one\nare gone from Brooklyn\nand I did\nnot care to have him write\nit because he did not know\nhim well enough personally\nso I decided to ask Mr\nWoodside and sent him\nyour note. At the time he\nwas very busy with preperations [preparations?]\nfor his anniversary and it was\nabout three weeks before I\nreceived an answer asking\nfor some items of information\nFinally he wrote that he\nhad written an article for\nthe Sentinel March number\nI send you his letter in\nexplanation for so doing. I\nalso send you a copy of the\nSentinel containing the obituary\nI am afraid it is not what\nyou desire but I cannot do\nany better now. I have been\nvery much afflicted all winter\nwith rheumatism in my right\nknee. Helen (we call her \"Nellie\") hurt\nher foot in Jany and\ndid not step on it for two months\nKatherine, the youngest, expects to\nbe married in June and they\nwill board with me I hope we\nmay hear often and know more\nof each other even on earth and\nnot fail to meet with the\ndear ones gone before in our\nEternal home in the heavenly\nLands. The girls join in love\n                  Your sister\n#PAGE 3\n                        [?] [Sample?]\nJames suffered\nmuch pain for\nthree months but\nwas in bed only\ntwo weeks and\nwas kept under\nthe influence of\nmorphine to keep\ndown convulsions\nbut he knew us\nall until very\nnear the last."

Sample is not a name. This letter does not seem to include one, therefore omitting it, to be converted to blank and then anonymous.

In [24]:
df$docauthorname <- gsub(" Sample","", df$docauthorname) 
unique(df$docauthorname)[0:50]

[1] "Edward Stanley"            ""                         
 [3] "James Kelly"               "Alexander McCloy"         
 [5] "George Kirkpatrick"        "William Porter"           
 [7] "G.R. Wood"                 "Alexander Robb"           
 [9] "N. Carrothers"             "James P. Breeze"          
[11] "Elisha & Lois Parish"      "Robert McClorg "          
[13] "O Bouligny"                "Martha Wilson"            
[15] "James Heather"             "Richard Rothwell"         
[17] "Kate Brown"                "A. Jackson"               
[19] "Mary Dwyer"                "Edward McNally"           
[21] "E. Megaw"                  "James Horner"             
[23] "Samuel Shaw"               "William Smith"            
[25] "James Ormond"              "A. Aitken"                
[27] "Jim Swan"                  "Philip Formby"            
[29] "Samuel James McCreery"     "William W Shaw"           
[31] "Wm. Heather"               "William Parke"            
[33] "Alex McLeod"               "Isabella Weir"            
[35] "Leydd McCrory "            "William W. Shaw"          
[37] "John Parks"                "I. Pembe"                 
[39] "William Montgomery"        "Hami"                     
[41] "James and Margaret Carson" "Thomas Armstrong"         
[43] "Solomon Moody"             "James Barbour"            
[45] "Andrew Gibson"             "E. Rothwell"              
[47] "John McBride"              "George Doyle"             
[49] "E. Cochrane"               "George R. Wood"

In [25]:
df$docauthorname[df$docauthorname==""] <- "Anonymous"
unique(df$docauthorname)[0:50]

[1] "Edward Stanley"            "Anonymous"                
 [3] "James Kelly"               "Alexander McCloy"         
 [5] "George Kirkpatrick"        "William Porter"           
 [7] "G.R. Wood"                 "Alexander Robb"           
 [9] "N. Carrothers"             "James P. Breeze"          
[11] "Elisha & Lois Parish"      "Robert McClorg "          
[13] "O Bouligny"                "Martha Wilson"            
[15] "James Heather"             "Richard Rothwell"         
[17] "Kate Brown"                "A. Jackson"               
[19] "Mary Dwyer"                "Edward McNally"           
[21] "E. Megaw"                  "James Horner"             
[23] "Samuel Shaw"               "William Smith"            
[25] "James Ormond"              "A. Aitken"                
[27] "Jim Swan"                  "Philip Formby"            
[29] "Samuel James McCreery"     "William W Shaw"           
[31] "Wm. Heather"               "William Parke"            
[33] "Alex McLeod"               "Isabella Weir"            
[35] "Leydd McCrory "            "William W. Shaw"          
[37] "John Parks"                "I. Pembe"                 
[39] "William Montgomery"        "Hami"                     
[41] "James and Margaret Carson" "Thomas Armstrong"         
[43] "Solomon Moody"             "James Barbour"            
[45] "Andrew Gibson"             "E. Rothwell"              
[47] "John McBride"              "George Doyle"             
[49] "E. Cochrane"               "George R. Wood"

In [26]:
# Omit letter from/by
df$docauthorname <- gsub(".*letter from ","", df$docauthorname)
df$docauthorname <- gsub(".*Letter from ","", df$docauthorname)
df$docauthorname <- gsub(".*letter by ","", df$docauthorname)
df$docauthorname <- gsub(".*Letter by ","", df$docauthorname)
unique(df$docauthorname)[0:50]

[1] "Edward Stanley"            "Anonymous"                
 [3] "James Kelly"               "Alexander McCloy"         
 [5] "George Kirkpatrick"        "William Porter"           
 [7] "G.R. Wood"                 "Alexander Robb"           
 [9] "N. Carrothers"             "James P. Breeze"          
[11] "Elisha & Lois Parish"      "Robert McClorg "          
[13] "O Bouligny"                "Martha Wilson"            
[15] "James Heather"             "Richard Rothwell"         
[17] "Kate Brown"                "A. Jackson"               
[19] "Mary Dwyer"                "Edward McNally"           
[21] "E. Megaw"                  "James Horner"             
[23] "Samuel Shaw"               "William Smith"            
[25] "James Ormond"              "A. Aitken"                
[27] "Jim Swan"                  "Philip Formby"            
[29] "Samuel James McCreery"     "William W Shaw"           
[31] "Wm. Heather"               "William Parke"            
[33] "Alex McLeod"               "Isabella Weir"            
[35] "Leydd McCrory "            "William W. Shaw"          
[37] "John Parks"                "I. Pembe"                 
[39] "William Montgomery"        "Hami"                     
[41] "James and Margaret Carson" "Thomas Armstrong"         
[43] "Solomon Moody"             "James Barbour"            
[45] "Andrew Gibson"             "E. Rothwell"              
[47] "John McBride"              "George Doyle"             
[49] "E. Cochrane"               "George R. Wood"

In [27]:
toMatch <- c("\\[|\\]", "\\(|\\)")
unique (grep(paste(toMatch,collapse="|"), 
                        df$docauthorname, value=TRUE))

[1] "H.Y. [Hami"                "Agnes Shakespeare (Nesta)"
 [3] "B. F. Butler [Washin"      "[William McElderry"       
 [5] "[Hami"                     " [Michigan"               
 [7] "John Mortan [Mo"           "[Sandy Robb"              
 [9] "Martha [Pozi"              "Andrew [John"             
[11] "[Geoffrey Blakely"

In [28]:
# Code for testing method bypassed
#x <- "H.Y. [Hami"
df$docauthorname <- gsub(".*\\[.*","", df$docauthorname) #Brackets and contents thereof
#gsub("\\[|\\]", "", x) #Just the brackets
#x #Original

#y <- "Agnes Shakespeare (Nesta)"
df$docauthorname <- gsub("\\(.*\\)","", df$docauthorname) #Parantheses and contents thereof
#gsub("\\(|\\)", "", y) #Just the parantheses
#y #Original

unique(grep(paste(toMatch,collapse="|"), df$docauthorname, value=TRUE))

character(0)

In [29]:
df$docauthorname[df$docauthorname==""] <- "Anonymous"
unique(df$docauthorname)[0:50]

[1] "Edward Stanley"            "Anonymous"                
 [3] "James Kelly"               "Alexander McCloy"         
 [5] "George Kirkpatrick"        "William Porter"           
 [7] "G.R. Wood"                 "Alexander Robb"           
 [9] "N. Carrothers"             "James P. Breeze"          
[11] "Elisha & Lois Parish"      "Robert McClorg "          
[13] "O Bouligny"                "Martha Wilson"            
[15] "James Heather"             "Richard Rothwell"         
[17] "Kate Brown"                "A. Jackson"               
[19] "Mary Dwyer"                "Edward McNally"           
[21] "E. Megaw"                  "James Horner"             
[23] "Samuel Shaw"               "William Smith"            
[25] "James Ormond"              "A. Aitken"                
[27] "Jim Swan"                  "Philip Formby"            
[29] "Samuel James McCreery"     "William W Shaw"           
[31] "Wm. Heather"               "William Parke"            
[33] "Alex McLeod"               "Isabella Weir"            
[35] "Leydd McCrory "            "William W. Shaw"          
[37] "John Parks"                "I. Pembe"                 
[39] "William Montgomery"        "Hami"                     
[41] "James and Margaret Carson" "Thomas Armstrong"         
[43] "Solomon Moody"             "James Barbour"            
[45] "Andrew Gibson"             "E. Rothwell"              
[47] "John McBride"              "George Doyle"             
[49] "E. Cochrane"               "George R. Wood"

In [30]:
df %>% 
filter(docauthorname=="Incomplete:  ") %>% 
select(docid)

docid
1 38606

In [34]:
read_file(paste0("/Users/alaynemoody/Dropbox/GradStudies/Flinders/Dissertation/IED/", "38606.txt"))

[1] "                             Stockton Sept 24th\r\n                                         1800\r\n\r\nDear Sister\r\n\r\nI recieved [received?] yours Saturday\r\nwith one From Home.  I am Still anxious\r\nabout Mother as it says she is not Yet\r\nfully recovered yet  I was surprised to\r\n[hear?] that Mr Kimball had [mentioned?]\r\nme I have never met him nor do not care\r\nto I am now In The Yard as [Attendant?]\r\n[There?] but expect a permenant [permanent?]\r\nposition of night watching as soon as a\r\nvancancy ocurs [occurs?] I have succeded\r\n[succeeded?] beyond my expectations I\r\ndid have only Temporary Nightwatching\r\nbut did not think it necessary to Say\r\nanything to that effect everybody Seems\r\nkind to me and I endeavour to do my\r\nduty to my Fellow creatures as far as [In?]\r\n[me?] lays Hall 12 was well Furnished when I\r\nleft Miss Gaddam merely wants to make a\r\ndisplay I myself Heard her criticize Miss\r\nHapleh for Being extravagant on 15 then\r\nshe turns round and does The Same how is\r\nLizzie Proctor and How do you like Dr [Sahsbury?]\r\n[Salisbury?] by the way does he ever ask for\r\nme I want you to take particular pains and\r\ntell Them that I do not do any kind of work\r\nand get done.  The pay almost The yet I tell\r\nyou I do not regret my journey have a Beautiful\r\nroom all to myself everything is so regulated and\r\nSo quiet The beds I told you of are [straw?]\r\nbeds The muff & Belt & neck strap is used very\r\nFreely I in turn warn you what to do in respect\r\nto what I send you be careful about what you say\r\nand who you repeat it too I Just wish you were\r\nHere but I will See a chance Sometime meanwhile\r\nyou be on The lookout....\r\n\r\n"

In [31]:
df %>%
filter(docauthorname=="Incomplete: ") %>% 
select(docid, description)

docid
1 24149
2 32432
3 32652
4 35929
5 37323
6 40815
7 40882
8 44825
9 51927
  description                                                                                                   
1 Incomplete: [?], Michigan To Annie Weir, [?];Copyright Retained by Mrs Linda Weir; CMSIED 9906061             
2 Incomplete: [W.J. Weir?], Fresno, to "My Dear Annie";Copyright Retained by Mrs Linda Weir; CMSIED 9906160     
3 Incomplete: [?], Edenclaw, Co. Fermanagh to "Dear Sister";Copyright Retained by Mrs Linda Weir; CMSIED 9906177
4 Incomplete: [Bella Weir?] to "Dear Mother, Sisters Bros";Copyright Retained by Mrs Linda Weir; CMSIED 9906155 
5 Incomplete: [W. Weir?], Fresno, to "Dear Annie";Copyright Retained by Mrs Linda Weir; CMSIED 9906165          
6 Incomplete: [W.J. Weir?], Fresno, to "Dear Annie";Copyright Retained by Mrs Linda Weir; CMSIED 9906169        
7 Incomplete: [?], Michigan to Annie Weir, Pontiac;Copyright Retained by Mrs Linda Weir; CMSIED 9906170         
8 Incomplete: [?] [New Brunswick?], to "My very dear Sister",; PRONI D 1792/; CMSIED 9909292                    
9 Incomplete: [W.J. Weir?], Fresno, to "My Dear Annie";Copyright Retained by Mrs Linda Weir; CMSIED 9906167

In [32]:
docids <- c("32432", "40815", "51927")
df$docauthorname[df$docid %in% docids] <- "W.J. Weir"

docids <- c("35929")
df$docauthorname[df$docid %in% docids] <- "Bella Weir"

docids <- c("37323")
df$docauthorname[df$docid %in% docids] <- "W. Weir"

docids <- c("24149", "32652", "40882", "44825")
df$docauthorname[df$docid %in% docids] <- "Anonymous"

df %>%
filter(docauthorname=="Incomplete: ") %>% 
select(docid, description)

docid description

In [33]:
df %>% 
filter(docauthorname=="Philadelphia.") %>% 
select(docid, description)

docid
1 35118
2 35820
3 41043
4 43633
  description                                                                                                      
1 Extract of a Letter from Philadelphia.;The Belfast Mercury or Freeman's Chronicle 30th Sept 1783.; CMSIED 9407168
2 Extract of a Letter from Philadelphia.;The Northern Star, July 6th to July 9th 1795.; CMSIED 9408215             
3 Extract of a Letter from Philadelphia.;The Belfast Mercury, 27th April 1784.; CMSIED 9407189                     
4 Extract of a Letter from Philadelphia.;The Belfast Mercury 28th November 1783.; CMSIED 9407176

These are all published letters, which is ok in principal. But let's check out the content.

In [38]:
read_file(paste0("/Users/alaynemoody/Dropbox/GradStudies/Flinders/Dissertation/IED/", "43633.txt"))

[1] "Extract of a letter from Philadelphia, to a merchant\nin Belfast, Sept. 24 1783.\n\"I have not experienced much civilities or attention\nfrom any of my introductory letters here\nthis however you must not think singular as I am\nnot alone in this remark, it is the treatment almost\nevery Irishman has received. Hospitality and friendship,\nthe former characteristic of America,\nhas fled the land. The merchants are jealous\nof evory [every?] person that comes here who has the\nappearance of setting among them, and it is incredible\nhow reserved they are in conversation,\nand with what duplicity they guard themselves\non any matter of trade. I despise them for attempting\nto discharge their army without paying\nthem three years arrears now due, or making\nany provisions for those disabled in service. The\nsoldiers took the alarm and rose to pay themselves,\nbut where [were?] quelled by fair promises, which\nperhaps may be their only reward at last, in\nshort the wealthy part of the people are a selfish\nungrateful set.\n      \"It is very distressing to see so many of our\nbrave infatuated countrymen of every description\ncrowding here daily, in expectation of making a\nfortune in the land of liberty, almost on their arrival;\nbut, poor deluded wretches! did they\ncalculate right, they would find that living here\nruns off with the extravagant wages they receive,\nand a stranger coming here runs a risk of starving\nif his purse is light, before he meets with employment.\nThe exportation of servants from Ireland is shocking;\nthey can have no choice in their matter, and very\noften they are treated little better than\nnegroes during their their servitude;\nfor a master may, for the smallest offence, put\nhis indented servant into the work-house and feed\nhim there during his pleasure on bread and water,\nwithout the servant having the smallest\nredress; In short, if a man has prudence, he may\nlive better and enjoy more real staisfaction on\n100l [Ã…Â“?] a year in Ireland, than on 500l. [Ã…Â“?]\nsterling here.\"\n"

These are all fine to include as they are of a personal nature. I will simply recode docauthorname to "anonymous".

In [34]:
df$docauthorname[df$docauthorname=="Philadelphia."] <- "Anonymous"
df %>% 
filter(docauthorname=="Philadelphia.") %>% 
select(docid, description)

docid description

In [35]:
df %>% 
filter(docauthorname=="Letter") %>% 
select(docid, description)

docid
1 33451
2 35325
3 40831
4 46536
  description                                                                                                                  
1 Letter to Albert Estopinal, [Washington D.C.?];Copyright Retained by Brendan O'Reilly; CMSIED 9808568                        
2 Letter to the Editor on American Foreign and Domestic Policy;The Armagh Guardian, Tuesday, September 16, 1845; CMSIED 9407149
3 Letter to Emigrants from British Vice-Consul, New York;The Belfast Newsletter, Tuesday, 22 October, 1833; CMSIED 200443      
4 Letter to John Humphrey in South Carolina.; PRONI D3561/; CMSIED 9306115

Again, checking on content.

In [41]:
read_file(paste0("/Users/alaynemoody/Dropbox/GradStudies/Flinders/Dissertation/IED/", "46536.txt"))

[1] "                PAPERS OF PROF. E. R. R. GREEN\n\n\n\n(Copies of emigrant letters collected by and sent to E. R. R.\nGreen as part of his research project on emigration)\n\n\n\n                Deposited by Dr, P. R. Green\n\n\n\n\n\n[The following letter was handwritten to John Humphrey in\nAmerica and dated March 23rd 1833. The source and the letter\nwriter are unknown. The photocopied copy of the letter is\nstamped \"From the original in The South Carolina Library.\nPermission is required for duplication or Publication\".]\n\n                                  Crosscannon March 23rd 1833\nDear Brother and Sister I again sit down to write to you we\nare all in good health at present thanks be to god for all his\nblessings to us his undeserving creatures\n  I hope these few lines will find you and family enjoying the\nsame great blessings I have thoughn [thought?] [missing]\n[missing] getting a letter from you we received no letters\nfrom you these eleven months past the last letter we received\nbore Date Feb [February?] 12-1832 in which you stated you had\nwrote [written?] a letter some time before which we never\nreceived we were sorry to hear of your sickness in the summer\ntime and also of the tremmur [tremor?] of your hand which makes\nus often think [missing] either not contented or it is not a\nhealthy [missing] which reason or are they more un [missing]\n[missing] from you therefore I hope you [missing] [missing]\nletters as [missing] as possible [missing] [missing] John\n[missing] like [missing] [missing] so that fath [missing]\n[missing] Dear B [missing]\n\n\nDear Brother and Sister be so kind as state [sic] in your next\nletter the affairs of your country or if the choleramorbus\nwhich is the name the Medical men in this country have ascrib\ned [ascribed?] to it we have heard of it being very bad in the\ngrea ter [greater?] parts of America but is anxious to know\n[if?] it has reached your border it has been somewhat felt in\nAntrim it has been Fatal in B[elfast?] Dublin and Newry also in\nEngland and Scotland Larn [Larne?] Ballymena, Ballymoney it was\n#PAGE 2\nalso alarming in Antrim for a few days Mrs Magill went to bed\nin good health at nine o'clock and [missing] [missing] at twelve\nand felt herself somewhat [missing] [missing] the doctors were\napplied to and the cur[missing] [missing] was in vain [missing]\nfive in the [missing] [missing] it was a [missing]ing to\n[missing] [missing] place [missing]t sam[missing]\n[missing]                                  th her[missing]\n\n\n\n\nDear Brother and Sister there are a great many alterations in\nthis country since you left it trade is still getting worse\nhere Victualing is very low here this season potatoes best price\n14D [?] but meal 9s Do [?] pork During the winter w[missing]\n[missing] om [from?] 34s to 38s [?] cw [hundred weight?] but is\nnow from 28s to 33s Do [?] [torn] cattle is very high butter\nDuring the summer was from 8D to 10D [?] lb [pound?] D--r [Dear?]\nSister Pam [missing] to you that my Uncle Samuel has sold [his?]\nfarm [missing] cannon the same man bought it that bought [missing]\nFlemings of potters walls Mr. Montgomery Esqr [Esquire?] and\nUncle got 1040 pounds for his farm and he has bought David [---?]\nand as I also stated to you before William Fleming got [missing]\nhis also Uncle James Hus[ton?] has sold his in R[missing]\n[missing] pound for his farm Mr. Macaddan of Belfast and [missing]\nin his own [torn] usual and it, [missing] [missing] how i[torn]\nwith him [missing] [missing] doing well as [missing]\n     [missing]\n\n[Addressed to:]\n\nJohn Humphry\nSouth Carolina\n[missing]chter District\n    [missing] Postoffice\n    [missing]merica [America?]"

Only 40831 is of a personal nature but not written in North America. The others are written in people's professional capacities or offer political commentary. Removing them all.

In [36]:
nrow(df)
docids <- c("33451", "35325", "40831", "46536")
df <- df[!df$docid %in% docids,]
nrow(df)

[1] 3055

[1] 3051

In [37]:
df %>% 
filter(grepl("Incomplete", docauthorname)) %>% 
select(docid, description)

docid
1  21324
2  23201
3  23310
4  25369
5  27824
6  29751
7  30112
8  32097
9  36625
10 38191
11 38606
12 40130
13 43840
14 52472
   description                                                                                                                                        
1  Incomplete: [Isabella Moore?] San Francisco, to "Dear Sister";Copyright Retained by Mrs Linda Weir; CMSIED 9906156                                 
2  Incomplete: [?] Kalamazoo, To Annie Weir, [?];Copyright Retained By Mrs Linda Weir; CMSIED 9906119                                                 
3  Incomplete letter U.S.A. to "Dear William John", Shell Creek.; PRONI D 1558/1/1; CMSIED 9708168                                                    
4  Incomplete letter [Indiana?] to "My Dear Mother".;Donated by Mrs. I. J. Beattie; CMSIED 9904184                                                    
5  Incomplete: [?] Birmingham, To "Dear Sister";Copyright Retained By Mrs Linda Weir; CMSIED 9906118                                                  
6  Incomplete: [?] California To "Dear Sister";Copyright Retained By Mrs. Linda Weir; CMSIED 9906122                                                  
7  Incomplete: [?] Ardvarney, to "My Dear Sister";Copyright Retained by Mrs Linda Weir; CMSIED 9906095                                                
8  Incomplete: W.J. Weir, Fresno, to Annie Weir, Pontiac;Copyright Retained By Mrs Linda Weir; CMSIED 9906162                                         
9  Incomplete letter: Officer of the 46th to Irish Gentleman;The London-Derry Journal and General Advertiser, Friday, August9th, 1776.; CMSIED 9909238
10 Incomplete - [W.J. Weir?] Fresno, to "My Dear Annie";Copyright Retained by Mrs Linda Weir; CMSIED 9906164                                          
11 Incomplete: [Isabella Moore?] Stockton, to [Annie Weir?] [?];Copyright Retained by Mrs Linda Weir; CMSIED 9909198                                  
12 Incomplete Letter - J. Magill, Wyoming, To E. Mulgrew, Dungannon.;Copyright Retained by Seamus P. Lynch; CMSIED 9612199                            
13 Incomplete letter: William Love, Sarnia, Ontario, to "Dear Sir"; PRONI D 889/7/1; CMSIED 9909038                                                   
14 Incomplete: [W.J. Weir?] Washington Colony, to "My Dear Annie";Copyright Retained by Mrs Linda Weir; CMSIED 9906166

In [38]:
docids <- c("21324", "38606")
df$docauthorname[df$docid %in% docids] <- "Isabella Moore"

docids <- c("32097", "38191", "52472")
df$docauthorname[df$docid %in% docids] <- "W.J. Weir"

docids <- c("43840")
df$docauthorname[df$docid %in% docids] <- "William Love"

docids <- c("40130")
df$docauthorname[df$docid %in% docids] <- "J. Magill"

docids <- c("23201", "23310", "25369", "27824", "29751", "30112", "36625")
df$docauthorname[df$docid %in% docids] <- "Anonymous"

df %>% 
filter(grepl("Incomplete", docauthorname)) %>% 
select(docid, description)

docid description

In [39]:
df %>% 
filter(grepl("George Ritchie", docauthorname)) %>% 
select(docid, description)

docid
1 30953
2 38584
  description                                                                                   
1 George Ritchie, NY, to "My Dear Father & Mother",  Londonderry.; PRONI T3292/2; CMSIED 9406202
2 George Ritchie NY to James Ritchie, Co Londonderry; PRONI T3292/1; CMSIED 9406201

In [40]:
docids <- c("38584")
df$docauthorname[df$docid %in% docids] <- "George Ritchie"

In [41]:
#test <- df$docauthorname
#test %>% 
 #str_remove_all('\"') %>% 
  #str_squish() %>% 
#unique() %>% 
#sort()

df$docauthorname <- df$docauthorname %>% 
str_remove_all('\"') %>% 
str_squish()

In [42]:
# To inspect
vals <- c(#"American Letter", # Letter to editor, more like a collection of journal entries. Omit.
          #"An Account of a Visit", # This appears to be a letter from an individual to a congregation. Keep.
          "an American Officer", 
          #"An Emigrant in Chicago", # Personal letter to parents. Keep.
          "an Irish Emigrant", 
          #"An Irishman in Cal", # This appears to be an open letter, probably in an publication of some kind. Omit.
          #"Anderson Canada", # Personal letter. Keep but fix in cell below.
          #"Baltimore", # All four of these to be deleted because they are impersonal (e.g., business, organizational)
          #"Benjamin Neely Co. Derry To his Brother", #This appears to contain two letters, one from Benjamin and one from William, both in South Carolina
          #"Capt. F. R. M. Crozier", #Personal letter. Keep.
          #"Chancellor of the Duchy of Carlisle", # Letters of recommendation. Omit.
          #"Cheque paid by William Parke", #Promis to pay. Omit
          #"Co. Tyrone", # Sent from Ireland (not USA or Can). Omit.
          #"Cork", # Sent from Ireland (not USA or Can). Omit.
          #"Countess of Dufferin", # Personal letter. Keep but fix name.
          #"Craven County", #Personal letter from America. Keep but change name to Anonymous.
          #"Cumberland Co.", #Personal letter w/intro. Keep but correct name and delete intro (done)
          #"Danville", #Possibly published but personal, originally from one individual to his father. Keep but change to Anonymous.
          #"Description of the P", # Personal letter. Keep but change to Anonymous.
          #"Destruction of the Irish Regiment at Fredericksburg.", #Personal letter that was later published. Keep but change to Anonymous.
          #"Diaries of James Harshaw", # Personal letter to his aunt. Keep but correct docauthorname
          #"Directions", #Personal letter later published. Keep but change to Anonymous.
          #"Dyer et al", #Business letter. Omit.
          #"Earl of Ava", #These appear to be all personal letters from USA or Canada. Keep but change name to Archie.
          #"Earl of Caledon", #Personal letter from Quebec. Keep but change name to Caledon.
          #"Emigrant Letter Regarding Conditions", #No content. Omit.
          #"Emigration", #Keep 30890 and change to Anonymous. Omit 43332.
          #"Envelope", # Just an envelope. Omit.
          #"Envelope:", # Just an envelope. Omit.
          #"Envelopes Sent To Rev J. Orr", # Just envelopes. Omit.
          #"Erin-Go-Bragh", # Letter to editor. Not personal. Omit.
          #"Ernest Cochrane Belfast", # Written in Belfast: Omit
          "Extract a Letter of a Recent Emigrant",
          "Extract an American Letter.",
          "Extract from a Gentleman Who Sailed on the Wilmin",
          "Extract from An Emigrant's Letter Discussing Problems in America.",
          "Extract Local Paper of a Letter Printed In America.",
          "Extract of a Letter Newry Concerning Returning Irishmen.",
          "Extract of a Letter on Canadian Emigration",
          "Extract of a Letter Oregon Terr",
          "Extract Of A Letter Philadelphia.",
          "Extract One of the Drennan Letters",
          "Extracts a Letter Dated San Francisco",
          "Extracts an Emigrant Letter New Orleans",
          "Extracts from Letter - Writer Unknown.",
          "Extracts of letters from New York",
          "Impressions of Cal",
          "Irish Emigrant Pigua",
          "Irishmen In America - Important.",
          "Irishmen in Virginia in 1784",
          "Joseph Philadelphia",
          "Letter",
          "Letter Concerning Problems of Emigration.",
          "Letter Mrs. Martha. L. Weyman Re the Savage family.",
          "Letter of Thanks by Belfast Printers",
          "Letter of Thanks from Passengers of Ship Prosperity",
          "Letter of Thanks from Passengers of Ship Riverdale",
          "Letter Re - The Jane McCullagh Estate",
          "Letter written by Thomas Gribbin",
          "Letters America",
          "Letters from America",
          "Letters from Mrs. Lizzie Street",
          "Letters from the McGinty and Crosby families",
          "Letters of the FitzGerald Family of Co. Tipperary",
          "Limerick emigrant",
          "Lord Alexander Caledon", #If ok, change to form below
          "Lord Caledon", 
          "Loving Mother & Sisters",
          "Lowell Emigrant",
          "ME",
          "Member of the Coman family",
          "More Returned Emigrants from United States.",
          "Mortimer & Harris",
          "Moyers & Consaul",
          "My Life in the Army William McCarter",
          "New Orleans",
          "New York",
          "Newcastle",
          "NY",
          "One of The Drennan Letters",
          "Oregon .",
          "Papers of Prof. E. R. R. Green.",
          "Passenger on Board the Ship Faithful Steward",
          "Passenger on S.S. Caledonia",
          "Passenger on Ship Iphigenia.",
          "Passenger who Sailed on the Ship Josephine",
          "Pembe",
          "Pennsylvania",
          "Petition",
          "Petition of John Caldwell Senior",
          "Philadelphia",
          "Poscript",
          "Postcard from S.",
          "Postcard Ralph",
          "Prospects",
          "Prospects of Emigrants in Canada.",
          "Protestant Episcopal Church in the United States",
          "pupils",
          "Quebec",
          "Receipt from James Clarke",
          "Request",
          "Return Migration from America",
          "Return of Emigrants from America.",
          "Returned Emigrants from United States.",
          "Salvation Army Emigrants",
          "Savannah",
          "Sep",
          "Sir Francis Hincks",
          "Sister Bell",
          "Sister M. Mamerta",
          "Sister Rose",
          "Smiley",
          "Son in America",
          "South Carolina",
          "Susan McAleece County Tyrone",
          "Susquehanna",
          "The",
          "The Anderson Brothers",
          "The Emigrant.",
          "The Estate of James Denny",
          "The Fenian Brotherhood Letter",
          "The Land Question - Rev. Mr Mullen",
          "The North West Terr",
          "The Presbyterian Church in America.",
          "The Privateer",
          "The Province of New York",
          "Things as They Are in The United States.",
          "Travels Through The United States",
          "Vere Foster",
          "Vere Foster and Irish Emigration.",
          "Vote of Thanks the Passengers of the Arethusa.",
          "W",
          "We")

In [43]:
df %>% 
filter(df$docauthorname %in% vals) %>% 
select(docid, docauthorname) %>% 
arrange(docauthorname)

docid docauthorname                                                    
1   49121 Extract Local Paper of a Letter Printed In America.              
2   42440 Extract Of A Letter Philadelphia.                                
3   29386 Extract One of the Drennan Letters                               
4   39371 Extract a Letter of a Recent Emigrant                            
5   21992 Extract an American Letter.                                      
6   43818 Extract from An Emigrant's Letter Discussing Problems in America.
7   43843 Extract from a Gentleman Who Sailed on the Wilmin                
8   28347 Extract of a Letter Newry Concerning Returning Irishmen.         
9   49043 Extract of a Letter Oregon Terr                                  
10  37191 Extract of a Letter on Canadian Emigration                       
11  52610 Extracts a Letter Dated San Francisco                            
12  36056 Extracts an Emigrant Letter New Orleans                          
13  53395 Extracts from Letter - Writer Unknown.                           
14  41708 Extracts of letters from New York                                
15  40977 Impressions of Cal                                               
16  27585 Irish Emigrant Pigua                                             
17  22467 Irishmen In America - Important.                                 
18  35058 Irishmen in Virginia in 1784                                     
19  37841 Joseph Philadelphia                                              
20  21462 Letter                                                           
21  50957 Letter Concerning Problems of Emigration.                        
22  43050 Letter Mrs. Martha. L. Weyman Re the Savage family.              
23  25221 Letter Re - The Jane McCullagh Estate                            
24  22330 Letter of Thanks by Belfast Printers                             
25  36313 Letter of Thanks from Passengers of Ship Prosperity              
26  49217 Letter of Thanks from Passengers of Ship Riverdale               
27  33918 Letter written by Thomas Gribbin                                 
28  40215 Letters America                                                  
29  33455 Letters from America                                             
30  22052 Letters from Mrs. Lizzie Street                                  
⋮   ⋮     ⋮                                                                
96  49820 South Carolina                                                   
97  25416 Susan McAleece County Tyrone                                     
98  22843 Susquehanna                                                      
99  43495 The                                                              
100 22550 The Anderson Brothers                                            
101 29429 The Emigrant.                                                    
102 27968 The Estate of James Denny                                        
103 27775 The Fenian Brotherhood Letter                                    
104 35188 The Land Question - Rev. Mr Mullen                               
105 29904 The North West Terr                                              
106 24239 The Presbyterian Church in America.                              
107 36630 The Privateer                                                    
108 49262 The Province of New York                                         
109 42464 Things as They Are in The United States.                         
110 47939 Travels Through The United States                                
111 23334 Vere Foster                                                      
112 27123 Vere Foster                                                      
113 28333 Vere Foster                                                      
114 29312 Vere Foster                                                      
115 37945 Vere Foster                                                      
116 46183 Vere Foster                               

In [50]:
text <- read_file(paste0("/Users/alaynemoody/Dropbox/GradStudies/Flinders/Dissertation/IED/", "36501.txt"))
cat(text)

                         75 Fitzwilliam Place
                          Belfast May 15, 82 [1882?]

My dear Kitty
           I should have thanked
you long ago, for your very
kind letter. It is awfully
goood of you, old girl, to take
so much interest in me, as to
give me advice. And I don't
think it will be altogether
thrown away. But one thing
I want to say - any wrong
I have done was single
handed. No companions could
lead me. And id any blame
is going, "freeze" it on to me.
    I brought several of my
friends to see four paintings
They did not know I knew
"Miss Finlay", and they praised them.
    It is a fact I am leaving
town. My office is closed, &
my things sold; so I will do
a "shunt" some of these days
Its better for everybody, as
one of my old rambling fits
is on me. Where it will lead
me to I don't know yet, but
I think I will light on my
feet!!      I am so glad
John is well. He is a thorough
good fellow, and has a big
heart. Friday night I saw
Albert off. He went away
with 

In [44]:
# To modify
df$docauthorname[df$docauthorname==""] <- "Anonymous"
df$docauthorname[df$docauthorname=="& Mary Boyd"] <- "Mary Boyd"
df$docauthorname[df$docauthorname=="a Young Man Who Sailed Belfast"] <- "Anonymous"
df$docauthorname[df$docauthorname=="Alex Borrowman Quebec"] <- "Alex Borrowman"
df$docauthorname[df$docauthorname=="Arthe Dunamanagh To Mrs A.W. Smyth"] <- "Arthe Dunamanagh"
df$docauthorname[df$docauthorname=="B.F.Butler"] <- "B.F. Butler"
df$docauthorname[df$docauthorname=="George Farrelly To Dear Aunt Sarah"] <- "George Farrelly"
df$docauthorname[df$docauthorname=="George Hayes Farrelly New York City"] <- "George Hayes Farrelly"
df$docauthorname[df$docauthorname=="J. Banks Re"] <- "J. Banks"
df$docauthorname[df$docauthorname=="J. Cochrane Philadelphia"] <- "J. Cochrane"
df$docauthorname[df$docauthorname=="James Horner Philadelphia"] <- "James Horner"
df$docauthorname[df$docauthorname=="John Ferguson Philadelphia"] <- "John Ferguson"
df$docauthorname[df$docauthorname=="John S. Sinclair Cal"] <- "John S. Sinclair"
df$docauthorname[df$docauthorname=="John Wightman jun."] <- "John Wightman"
df$docauthorname[df$docauthorname=="Joseph Carrothers Canada"] <- "Joseph Carrothers"
df$docauthorname[df$docauthorname=="Joseph Carrothers London Canada"] <- "Joseph Carrothers"
df$docauthorname[df$docauthorname=="Maggie Martin 3122 Rhodes Ave. Chicago To Her Aunt Ballyfounder Portaferry"] <- "Maggie Martin"
df$docauthorname[df$docauthorname=="Margaret Hughes Philadelphia"] <- "Margaret Hughes"
df$docauthorname[df$docauthorname=="Mary Anderson Chattanooga Tennessee"] <- "Mary Anderson"
df$docauthorname[df$docauthorname=="Matilda Ferguson Philadelphia"] <- "Matilda Ferguson"
df$docauthorname[df$docauthorname=="Nathaniel Carrothers Canada"] <- "Nathaniel Carrothers"
df$docauthorname[df$docauthorname=="Robert Campbell New York"] <- "Robert Campbell"
df$docauthorname[df$docauthorname=="Robert Campbell St Louis"] <- "Robert Campbell"
df$docauthorname[df$docauthorname=="Robert Robinson Chulahoma"] <- "Robert Robinson"
df$docauthorname[df$docauthorname=="Robert Smith Philadelphia"] <- "Robert Smith"
df$docauthorname[df$docauthorname=="Thomas McGinity New York"] <- "Thomas McGinity"
df$docauthorname[df$docauthorname=="William Beatty New York America"] <- "William Beatty"
df$docauthorname[df$docauthorname=="William Porter Chicago U.S.A."] <- "William Porter"
df$docauthorname[df$docauthorname=="William Stavely.Pennuslvania"] <- "William Stavely"
df$docauthorname[df$docauthorname=="William Stavely Pennsylvania"] <- "William Stavely"

# Fix from inspected docs (2024 Apr 26)
df$docauthorname[df$docauthorname=="Anderson Canada"] <- "Muriel"
df$docauthorname[df$docauthorname=="Benjamin Neely Co. Derry To his Brother"] <- "Benjamin and William Neely"
df$docauthorname[df$docauthorname=="Countess of Dufferin"] <- "Harriot"
df$docauthorname[df$docauthorname=="Craven County"] <- "Anonymous"
df$docauthorname[df$docauthorname=="Cumberland Co."] <- "John Taylor"
df$docauthorname[df$docauthorname=="Danville"] <- "Anonymous"
df$docauthorname[df$docauthorname=="Description of the P"] <- "Anonymous"
df$docauthorname[df$docauthorname=="Destruction of the Irish Regiment at Fredericksburg."] <- "Anonymous"
df$docauthorname[df$docauthorname=="Diaries of James Harshaw"] <- "James Harshaw"
df$docauthorname[df$docauthorname=="Directions"] <- "Anonymous"
df$docauthorname[df$docauthorname=="Earl of Ava"] <- "Archie"
df$docauthorname[df$docauthorname=="Earl of Caledon"] <- "Caledon"
df$docauthorname[df$docauthorname=="R. Campbell U.S.A."] <- "R. Campbell"
df$docauthorname[df$docid=="30890"] <- "Anonymous"


In [45]:
# To delete (permanently)
vals <- c("A List of Killed & Wounded in the Irish Brigade.", 
          "a Mr McCarver Describing Business in Oregon .",
          "Address",
          "Address from the Residents of Amherst Island",
          "Advice",
          "Agents of Latter-Day Saints To Officers of S.S. Minnesota",
          "Ballymacarrett Emigrant Weavers",
          "British Officer",
          "Capt P Dillon Concerning the Passage",
          "Genealogical Notes on: Alexander Reed & John Colhoun",
          "Halifax Repealers",
          "Jonathan Smyth Liverpool",
          "Lists of Caldwell Family Letters",
          "Memo of Will of William Redmond",
          "Merchants & Planters Bank",
          "Ship's Record Book.",
          "Song By An Irish Schoolmaster.",
          "Testimony of Passengers on the Washin",
          "American Letter", #From here on omitting items from inspected cell.
          "An Irishman in Cal",
          "Baltimore",
          "Chancellor of the Duchy of Carlisle",
          "Cheque paid by William Parke",
          "Co. Tyrone",
          "Cork",
          "Dyer et al",
          "Ernest Cockrane",
          "Ernest Cochrane Belfast",
          "Emigrant Letter Regarding Conditions",
          "Envelope",
          "Envelope:",
          "Envelopes Sent To Rev J. Orr",
          "Erin-Go-Bragh")

docids <- c("43332")

In [46]:
# Remove the above.
nrow(df)
df <- df[!df$docauthorname %in% vals,]
df <- df[!df$docid %in% docids,]
nrow(df)

[1] 3051

[1] 3013

In [47]:
# To delete (temporarily -- that is, until I've had an opportunity to check)

vals <- c("an American Officer",
          "an Irish Emigrant",
          "A. McFeeters & Bros",
          "Archbishop John Hughes",
          "Brooklyn",
          "Bryson and Robb Families",
          "Byrne Family",
          "Capt. He",
          "Capt. Samuel Smiley",
          "Colonel Leslie",
          "Cook & Cook",
          "Cook & Leach",
          "Cormac et al.",
          "E. & McCann",
          "E. Dunlop Peterborough.",
          "Extract a Letter of a Recent Emigrant",
          "Extract an American Letter.",
          "Extract from a Gentleman Who Sailed on the Wilmin",
          "Extract from An Emigrant's Letter Discussing Problems in America.",
          "Extract Local Paper of a Letter Printed In America.",
          "Extract of a Letter Newry Concerning Returning Irishmen.",
          "Extract of a Letter on Canadian Emigration",
          "Extract of a Letter Oregon Terr",
          "Extract Of A Letter Philadelphia.",
          "Extract One of the Drennan Letters",
          "Extracts a Letter Dated San Francisco",
          "Extracts an Emigrant Letter New Orleans",
          "Extracts from Letter - Writer Unknown.",
          "Extracts of letters from New York",
          "Impressions of Cal",
          "Irish Emigrant Pigua",
          "Irishmen In America - Important.",
          "Irishmen in Virginia in 1784",
          "J. Fisher & Sons",
          "Joseph Philadelphia",
          "Last letter received by the family of Capt. F. R. M. Crozier.",
          "Letter",
          "Letter Concerning Problems of Emigration.",
          "Letter Mrs. Martha. L. Weyman Re the Savage family.",
          "Letter of Thanks by Belfast Printers",
          "Letter of Thanks from Passengers of Ship Prosperity",
          "Letter of Thanks from Passengers of Ship Riverdale",
          "Letter on Emigration.",
          "Letter on Irish Emigration",
          "Letter Re - The Jane McCullagh Estate",
          "Letter written by Thomas Gribbin",
          "Letters America",
          "Letters from America",
          "Letters from Mrs. Lizzie Street",
          "Letters from the McGinty and Crosby families",
          "Letters of the FitzGerald Family of Co. Tipperary",
          "Limerick emigrant",
          "Lt. Col. Leslie",
          "Lord Alexander Caledon", #If ok, change to form below
          "Lord Caledon", 
          "Loving Mother & Sisters",
          "Lowell Emigrant",
          "ME",
          "Member of the Coman family",
          "Miller & Bonsal",
          "More Returned Emigrants from United States.",
          "Mortimer & Harris",
          "Moyers & Consaul",
          "My Life in the Army William McCarter",
          "New Orleans",
          "New York",
          "Newcastle",
          "NY",
          "One of The Drennan Letters",
          "Oregon .",
          "Owen & Honr. Henigan",
          "Papers of Prof. E. R. R. Green.",
          "Passenger on Board the Ship Faithful Steward",
          "Passenger on S.S. Caledonia",
          "Passenger on Ship Iphigenia.",
          "Passenger who Sailed on the Ship Josephine",
          "Pembe",
          "Pennsylvania",
          "Petition",
          "Petition of John Caldwell Senior",
          "Philadelphia",
          "Poscript",
          "Postcard from S.",
          "Postcard Ralph",
          "Prospects",
          "Prospects of Emigrants in Canada.",
          "Protestant Episcopal Church in the United States",
          "pupils",
          "Quebec",
          "R. Redmond in Ireland",
          "R. Moore Portadown",
          "Receipt from James Clarke",
          "Request",
          "Return Migration from America",
          "Return of Emigrants from America.",
          "Returned Emigrants from United States.",
          "Rev E T O'Neill",
          "Rev F Kirkpatrick",
          "Rev J G Mulholland",
          "Rev John Orr",
          "Rev. J. Orr",
          "Rev. John Orr",
          "Rutledge & Young",
          "Salvation Army Emigrants",
          "Sergeant Major John Laird",
          "Savannah",
          "Sep",
          "Sir Francis Hincks",
          "Sister Bell",
          "Sister M. Mamerta",
          "Sister Rose",
          "Smiley",
          "Son in America",
          "South Carolina",
          "Susan McAleece County Tyrone",
          "Susquehanna",
          "The",
          "The Anderson Brothers",
          "The Emigrant.",
          "The Estate of James Denny",
          "The Fenian Brotherhood Letter",
          "The Land Question - Rev. Mr Mullen",
          "The North West Terr",
          "The Presbyterian Church in America.",
          "The Privateer",
          "The Province of New York",
          "Things as They Are in The United States.",
          "Travels Through The United States",
          "Vere Foster",
          "Vere Foster and Irish Emigration.",
          "Vote of Thanks the Passengers of the Arethusa.",
          "W",
          "We"
)

In [48]:
nrow(df)
df <- df[!df$docauthorname %in% vals,]
nrow(df)

[1] 3013

[1] 2846

Are there multiple letters in some of the files?

In [49]:
df$docid[grepl("etters", df$docauthorname)]

[1] 49280

For now, the only item here that is relevant is 49280, which contains 8 letters and needs to be broken up. The status of the others will probably be resolved when I return to verify which letters to keep and which to omit.

<p>Examining the letters in the IED database (https://www.dippam.ac.uk/ied/records/[docid]) provided the folllowing information about these documents.</p>

<p>Multiple letters</p>
<ul><li>22052 (2 - include)</li>
<li>33434 (Intro alluding to multiple letters, possibly a Catholic family, some included elsewhere)</li>
<li>38514 (Intro alluding to multiple letters, included elsewhere in the collection)</li>
<li>40215 (Intro alluding to multiple letters that I don't see in the collection)</li>
<li>48704 (2 letter but one is from Ireland and the other extremely short -- basically just a 2-line greeting. Exclude)</li>
<li>49280 (8)</li>
</ul>

<p>One letter</p>
<ul><li>29386</li>
<li>33455(open letter in a publication)</li>
<li>35173</li>
<li>41708 (extract, published)</li>
</ul>    

<p>33434, 38514, 40215, and 48704 to be excluded from the NLP analysis but 33434 and 38514 will be read as part of the interpretive part of the analysis (to-do). Multiple letters will be separated into individual files. Single letters will be left as-is, aside from modifying the docauthorname to omit the suggestion that the items contains multiple letters.</p>

The code for adding lines (if necessary) is <br>

#Add rows for 22053 with same author info as for 22052.<br>
df <- rbind(df, df[df$docid=="22052",])<br>
nrow(df)


In [57]:
text <- read_file(paste0("/Users/alaynemoody/Dropbox/GradStudies/Flinders/Dissertation/IED/", "49280.txt"))
cat(text)

                Letters of Thomas Taylor of Ireland to his cousin Robert
                Taylor in America.  These are the last letters in the
                collection, the first is dated in 1799.
                                   Ballygoskin, 20th, May, 1826
Dear Bob:
I am yet in the land of the living, in March, 1824, I was very bad and
expected to die, my feet and legs was greatly swollen, about a month before
I took my bed my legs was greatly swoolen [swollen?], I found my legs
always hurt in bed, at length the water ossed [oozed?] out of them and wet
the bed, the latter end of April I got recovered and has enjoyed tolerable
good health ever since.
My wife has been in a delicate state of health for the most a year past but
is now feeling better, I believe somewhat touched with a liver complaint.
The rest of the family enjoys pretty good health.  You will be anxious to
know about my family; Thomas is about 5 feet 9 inches, slender make, very
like me, but has not such a prominent 

I will omit 49280 because the letters are sent from Ireland to the USA or Canada.

In [50]:
nrow(df)
docids <- c("49280")
df <- df[!df$docid %in% docids,]
nrow(df)

[1] 2846

[1] 2845

In [51]:
length(unique(df$docauthorname))
sum(nrow(df))
sort(table(df$docauthorname), decreasing = TRUE)
print(sort(unique(df$docauthorname)))

[1] 1312

[1] 2845


                         Anonymous                               Hami 
                               164                                 51 
                       R. Campbell                   Andrew Greenlees 
                                40                                 38 
                    James Buchanan                       Mary Cumming 
                                30                                 28 
                    Alexander Robb                     Roland Redmond 
                                20                                 20 
                            Archie                        John Walker 
                                19                                 17 
                      James Horner                   Richard Rothwell 
                                16                                 16 
                   Isabella Martin                   Thos. W. Coskery 
                                15                                 15 
     

   [1] "A"                                  "A & L Greenlees"                   
   [3] "A M'L Staveley"                     "A M'Leod Staveley"                 
   [5] "A McElheran"                        "A McFeeters"                       
   [7] "A S Woodburn"                       "A Wilson"                          
   [9] "A. A. Longstreet"                   "A. Aitken"                         
  [11] "A. Brown"                           "A. Browne"                         
  [13] "A. Campbell"                        "A. D. Cruickshank"                 
  [15] "A. Doran"                           "A. Greenlees"                      
  [17] "A. Hami"                            "A. Hunter"                         
  [19] "A. Jackson"                         "A. M."                             
  [21] "A. Mapherson"                       "A. McFeeters"                      
  [23] "A. S. Whitell"                      "A. S. Woodburn"                    
  [25] "A. Sinclair"        

In [52]:
df %>% 
filter(grepl("&", docauthorname)) %>% 
select(docauthorname) %>% 
unique()

docauthorname                    
1  Elisha & Lois Parish             
2  Nathaniel & Margaret Carrothers  
3  Samuel & John Mo                 
4  Jane Chambers & Alexander Park   
6  Maggie & Alice Martin            
7  R & J. Smyth                     
8  A & L Greenlees                  
9  John & Matilda Ferguson          
10 Nancy & Samuel Laird             
11 J. E. Orr & M. Orr               
12 Joseph & Mary McClorg            
13 Samuel Laird & Brothers          
14 Samuel & James Laird             
15 Ralph & Aggie                    
16 Mitilda Ferguson & Sarah Ferguson
17 Jane & James McCague             
18 John & Mitilda Ferguson          
19 T & A Hunter                     
21 Samuel & Margaratt Hall          
22 W. & E. Heather                  
23 M Brooks & A Cummins             
24 Thomas & Mary Gallagher          
25 John Ferguson & Mitilda Ferguson 
26 Will. & Ann Forrest              
28 James & Mary Toal                
29 Andrew & Lucy Greenlees          
30 Minor & Ashley                   
32 J Fife & D Stewart               
33 Samuel & Ann Nimicks             
34 R. & J. Anderson                 
36 Thomas & Ada Edgar               
38 J & C McLees                     
39 John & Ann Jane Nightingale      
40 James & Margaret Carson          
42 Samuel & Ann Nimks               
45 Wm & Robt Mann                   
46 Henry & Ruth Hutchison           
47 Patrick & Margaret Hall          
50 J.& A R                          
51 Robert & Jonathan Smith          
53 John & Jane Chambers             
55 Lucy & Andrew Greenlees          
57 George & Catherine Hunt          
58 Archibald & Mary McClure

In [53]:
df$test <- gsub("\\.(?=[A-Za-z])", ". ", df$docauthorname, perl = TRUE)

In [54]:
df %>% 
filter(grepl("\\.\\S{1,}", docauthorname))%>% 
select(docauthorname, test) %>% 
unique()

docauthorname       test                
1   G.R. Wood           G. R. Wood          
2   R.A. Taylor         R. A. Taylor        
3   W.J. Weir           W. J. Weir          
4   A.B. Mc Millan      A. B. Mc Millan     
5   S.J. Porter         S. J. Porter        
6   J.J. Elder          J. J. Elder         
7   D.S. Cooper         D. S. Cooper        
8   W.J. Campbell Allen W. J. Campbell Allen
10  W.G. Weir           W. G. Weir          
12  C.K. Breeze         C. K. Breeze        
13  J.M. Neely          J. M. Neely         
14  S.D. Moore          S. D. Moore         
15  L.W. Kelley         L. W. Kelley        
16  J.J.Elder           J. J. Elder         
17  H.B. Moody          H. B. Moody         
18  J.Moon              J. Moon             
19  G.M.Farrelly        G. M. Farrelly      
20  E.E. Griggs         E. E. Griggs        
22  M.E. Ling           M. E. Ling          
23  W.J.B. Hami         W. J. B. Hami       
24  J.Walker Burns      J. Walker Burns     
25  J.Wilson            J. Wilson           
26  E.O. Leech          E. O. Leech         
27  J.F. Coleman        J. F. Coleman       
29  A.W. Smyth          A. W. Smyth         
30  S.A. Williamson     S. A. Williamson    
32  W.H. Gove           W. H. Gove          
34  H.N. Rucker         H. N. Rucker        
35  C.A.Hutchinson      C. A. Hutchinson    
36  B.F. Butler         B. F. Butler        
⋮   ⋮                   ⋮                   
71  H.Riddle            H. Riddle           
75  W.J. Stavely        W. J. Stavely       
76  J.M. Skellern       J. M. Skellern      
77  J.T. Mahoney        J. T. Mahoney       
78  W.A Chambers        W. A Chambers       
79  A.S. Woodburn       A. S. Woodburn      
82  Mrs M.S. Cra        Mrs M. S. Cra       
84  A.C.D. Taylor       A. C. D. Taylor     
85  Mrs. A.W. Smyth     Mrs. A. W. Smyth    
86  W.Smith             W. Smith            
88  A.A. Longstreet     A. A. Longstreet    
89  R.Redmond           R. Redmond          
91  J.G. Hall           J. G. Hall          
92  J.W. Smith          J. W. Smith         
93  W.J. Jennings       W. J. Jennings      
94  R.H. Kelly          R. H. Kelly         
95  M.J. Stevens        M. J. Stevens       
98  E.B. Wheeler        E. B. Wheeler       
99  F.H. Pollexfen      F. H. Pollexfen     
100 A.Jackson           A. Jackson          
101 E.G. Kelly          E. G. Kelly         
104 N.Gibbons           N. Gibbons          
105 J.S. Montgomery     J. S. Montgomery    
108 J.& A R             J.& A R             
110 J.R. Savage         J. R. Savage        
111 Mrs J.C.Shepherd    Mrs J. C. Shepherd  
112 A.G.Wilson          A. G. Wilson        
113 William J.Stavely   William J. Stavely  
114 P.Doherty           P. Doherty          
119 W.J.C. Allen        W. J. C. Allen

In [55]:
df$docauthorname <- df$test

In [56]:
dfNames <- df

## Author Location

I want to isolate everything between the first comma and word "to"

In [57]:
#reset
df <- dfNames

In [58]:
df$test <- gsub("\\b[t|T]o\\b.*","", df$description) # Everything after the word to
df$test <- gsub("^[^,]*,", "", df$test) # Everything before before the first comma
df$test <- gsub("\\[|\\]", "",df$test) # Strip brackets
df$test <- gsub("\\?", "",df$test) # Strip question marks
df$test <- gsub("PRONI.*", "",df$test) #Strip biblio
df$test

[1] " Katawa, Canada "                                                                                                 
   [2] " Brooklyn, N.Y., "                                                                                                
   [3] " Desertmartin "                                                                                                   
   [4] " Pennsylvania, "                                                                                                  
   [5] " Toronto, "                                                                                                       
   [6] " U.S.A. "                                                                                                         
   [7] " Holly, Michigan "                                                                                                
   [8] " Near Panama, "                                                                                                   
   [9] " Ontario "                                                                                                        
  [10] " Concord, "                                                                                                       
  [11] " U.S.A. "                                                                                                         
  [12] "Robert McClorg Philadelphia "                                                                                     
  [13] " New Orleans "                                                                                                    
  [14] " Kingston, Canada, "                                                                                              
  [15] " Ontario, "                                                                                                       
  [16] " Montreal, Canada, "                                                                                              
  [17] " Jeffersonville, "                                                                                                
  [18] " Canada, "                                                                                                        
  [19] " Southfield, "                                                                                                    
  [20] " Independence, Iowa, "                                                                                            
  [21] " USA  "                                                                                                           
  [22] " , "                                                                                                              
  [23] " Philadelphia "                                                                                                   
  [24] " Chicago, Illinois, U.S.A., "                                                                                     
  [25] " Philadelphia "                                                                                                   
  [26] " New York, informant "                                                                                            
  [27] " Iowa City, "                                                                                                     
  [28] " Ballintur, Co Down, "                                                                                            
  [29] " New York "                                                                                                       
  [30] " Dunton Colorado "                                                                                                
  [31] " Jersey City, "                                                                                                   
  [32] " Chicago, Illinois, "                                                                                             
  [33] " Canada, "                                                 

In [59]:
df %>% 
filter(grepl("Co\\.|Co\\s", test)) %>% 
select(test) %>% 
unique()
#pull(docid)

test                     
1   Ballintur, Co Down,     
2   Co. Tyrone              
3   Rostrevor,Co Down       
4  Co. Tyrone               
5   Cahard, Co. Down        
6   Co Down,                
7   Co. Monaghan,           
8   Portaferry, Co. Down    
9   Co. Donegal,            
10  Ballintur, Co Down      
12  Co. Down                
13  Allegheny Co.           
14  Co. Fermanagh,          
15  Co. Meath,              
16  Washington Co. Pa       
17  Co. Antrim              
18  Co Tyrone               
19  Edenclaw, Co. Fermanagh 
21  Co. Antrim,             
22  Portaferry, Co. Down,   
24  Newcastle, Co.Down      
26  Donaghmore, Co Down;    
30 Benjamin Neely Co. Derry 
33 Wm. S. Crawford Co. Down 
34  Co.Donegal,             
35  Co. Londonderry         
39  Co. Donegal             
47  Co. Down,

There are no Colorados but there are some U.S. counties. Code this to USA then omit the rest.

In [60]:
docids <- df %>% 
filter(grepl("Co\\.|Co\\s", test)) %>% 
filter(!grepl("Allegheny|Washington", test)) %>% 
#select(test) %>% 
#unique()
pull(docid)

In [61]:
nrow(df)
df <- df[!df$docid %in% docids,]
nrow(df)

[1] 2845

[1] 2800

In [62]:
# Fix test for docid 52111 
df$test[df$test==" Springbrook, USA My Dearest Mother, Banbridge, Ireland; "]  <- "Springbrook, USA"

In [63]:
docids <- 
df %>% 
filter(grepl("England|Ireland|Wales|Australia|New Zealand|Scotland", test)) %>% 
#select(docid, test, description)
pull(docid)

In [64]:
nrow(df)
df <- df[!df$docid %in% docids,]
nrow(df)

[1] 2800

[1] 2771

In [65]:
df %>% 
filter(grepl("Canada", test)) %>% 
#select(docid, test, description) %>% 
nrow()
#pull(docid)

vals <- c("USA", "U\\.S\\.A\\.", "U\\.\\sS\\.\\sA\\.", "U\\.S\\.\\W")

length(df$test[grepl(paste(vals, collapse = "|"), df$test)])

[1] 156

[1] 365

In [66]:
# New variable for author location
df$authorLocation <- NA

#Recode Canada
rows = which(grepl('Canada', df$test)) # Get rows that meet condition
df$authorLocation[rows] <- "Canada" # Recode data

rows = which(grepl(paste(vals, collapse = "|"), df$test)) # Get rows that meet condition
df$authorLocation[rows] <- "USA" # Recode data

# Convert character vars to factor
df$authorLocation <- as.factor(df$authorLocation)

#Check counts
summary(df$authorLocation)

Canada    USA   NA's 
   156    365   2250

In [67]:
provinces <- c("Quebec", 
               "Alberta", 
               "Ontario", 
               "Nova Scotia", 
               "Newfoundland", 
               "Labrador", 
               "Saskatchewan", 
               "Prince Edward Island", 
               "Manitoba", 
               "British Columbia", 
               "Yukon", 
               "New Brunswick",
               "Northern Territories"
               )

In [68]:
df$authorLocation[grepl(paste(provinces, collapse = "|"), df$test)] <- "Canada"
summary(df$authorLocation)

Canada    USA   NA's 
   310    365   2096

In [69]:
df %>% 
filter(authorLocation=="Canada") %>% 
pull(test) %>% 
unique() %>% 
sort()

[1] "  Kingston, Canada, "                         
 [2] " \"Apollo\", Quebec "                         
 [3] " Alberta "                                    
 [4] " Alberta, "                                   
 [5] " Barrie, Ontario "                            
 [6] " Bay View, Canada West, "                     
 [7] " Big Bend Prairie, Canada, "                  
 [8] " Brackville, Canada "                         
 [9] " British Columbia "                           
[10] " British Columbia, "                          
[11] " Brockville, Ontario, "                       
[12] " Calgary, Canada, "                           
[13] " Canada "                                     
[14] " Canada West "                                
[15] " Canada West, "                               
[16] " Canada, "                                    
[17] " Canfield, Ontario "                          
[18] " Caufield, Ontario, "                         
[19] " Caulfield, Ontario "                         
[20] " Citadel, Quebec, Canada, "                   
[21] " Clanbrassil, Ontario "                       
[22] " Earl of Ava, Canada, "                       
[23] " Fredricton, New Brunswick "                  
[24] " Hamilton, Canada "                           
[25] " Huntington, Canada "                         
[26] " Huron County, Ontario, "                     
[27] " Jesuit Barracks, Quebec, "                   
[28] " Katawa, Canada "                             
[29] " Kildare, Canada, "                           
[30] " Kingston, Canada "                           
[31] " Kingston, Canada, "                          
[32] " Kingston, Ontario "                          
[33] " Kingston, Ontario, "                         
[34] " Lachute, Canada "                            
[35] " Lachute, Quebec, Canada: re Watson family.; "
[36] " London, Ontario "                            
[37] " Manitoba "                                   
[38] " Manitoba, "                                  
[39] " Mingan Camp, Quebec "                        
[40] " Mingan, Quebec, "                            
[41] " Montreal, Canada "                           
[42] " Montreal, Canada, "                          
[43] " N.W.T Canada "                               
[44] " N.W.T., Canada, "                            
[45] " New Brunswick, "                             
[46] " New Brunswick, Canada, "                     
[47] " Nicola Lake, Canada "                        
[48] " Nicola Lake, Canada, "                       
[49] " Nova Scotia, "                               
[50] " Off Banks of Newfoundland, "                 
[51] " Ontario "                                    
[52] " Ontario Canada "                             
[53] " Ontario, "                                   
[54] " Ontario, Canada "                            
[55] " Ontario, Canada, "                           
[56] " Ontario. "                                   
[57] " Ottawa, Canada "                             
[58] " Ottawa, Canada, "                            
[59] " Ouebec, Canada, "                            
[60] " Oxley, Ontario, Canada "                     
[61] " Peterborough, Canada, "                      
[62] " Peterborough, Ontario "                      
[63] " Peterscreek, Quebec, "                       
[64] " Petrolia, Canada, "                          
[65] " Petrolia, Ontario, "                         
[66] " Quebec "                                     
[67] " Quebec Citadel, "                            
[68] " Quebec, "                                    
[69] " Quebec, Canada, "                            
[70] " Richmond, Upper Canada, "                    
[71] " Sarnia, Ontario, "                           
[72] " Saskatoon, Canada, "                         
[73] " Smiths Falls, Ontario, Canada "              
[74] " St John, Canada, "                           
[75] " St John, New Brunswick "                     
[76] " St Johns, New Bruns

In [70]:
states <- statesUSA$State
df$authorLocation[grepl(paste(states, collapse = "|"), df$test)] <- "USA"
summary(df$authorLocation)

Canada    USA   NA's 
   310   1208   1253

In [71]:
# Now abbreviations
states01 <- as.character(statesUSA$Abbreviation)
states02 <- gsub('$', ',', states01)
states03 <- gsub(',', '.', states02)
states04 <- gsub('([A-Z])', '\\1.', states01)
states05 <- gsub('\\.$', '', states04)
states <- c(states01, states02, states03, states04, states05)
states <- gsub('^', ' ', states)
states

[1] " AL"   " AK"   " AZ"   " AR"   " CA"   " CO"   " CT"   " DE"   " DC"  
 [10] " FL"   " GA"   " HI"   " ID"   " IL"   " IN"   " IA"   " KS"   " KY"  
 [19] " LA"   " ME"   " MT"   " NE"   " NV"   " NH"   " NJ"   " NM"   " NY"  
 [28] " NC"   " ND"   " OH"   " OK"   " OR"   " MD"   " MA"   " MI"   " MN"  
 [37] " MS"   " MO"   " PA"   " RI"   " SC"   " SD"   " TN"   " TX"   " UT"  
 [46] " VT"   " VA"   " WA"   " WV"   " WI"   " WY"   " AL,"  " AK,"  " AZ," 
 [55] " AR,"  " CA,"  " CO,"  " CT,"  " DE,"  " DC,"  " FL,"  " GA,"  " HI," 
 [64] " ID,"  " IL,"  " IN,"  " IA,"  " KS,"  " KY,"  " LA,"  " ME,"  " MT," 
 [73] " NE,"  " NV,"  " NH,"  " NJ,"  " NM,"  " NY,"  " NC,"  " ND,"  " OH," 
 [82] " OK,"  " OR,"  " MD,"  " MA,"  " MI,"  " MN,"  " MS,"  " MO,"  " PA," 
 [91] " RI,"  " SC,"  " SD,"  " TN,"  " TX,"  " UT,"  " VT,"  " VA,"  " WA," 
[100] " WV,"  " WI,"  " WY,"  " AL."  " AK."  " AZ."  " AR."  " CA."  " CO." 
[109] " CT."  " DE."  " DC."  " FL."  " GA."  " HI."  " ID."  " IL."  " IN." 
[118] " IA."  " KS."  " KY."  " LA."  " ME."  " MT."  " NE."  " NV."  " NH." 
[127] " NJ."  " NM."  " NY."  " NC."  " ND."  " OH."  " OK."  " OR."  " MD." 
[136] " MA."  " MI."  " MN."  " MS."  " MO."  " PA."  " RI."  " SC."  " SD." 
[145] " TN."  " TX."  " UT."  " VT."  " VA."  " WA."  " WV."  " WI."  " WY." 
[154] " A.L." " A.K." " A.Z." " A.R." " C.A." " C.O." " C.T." " D.E." " D.C."
[163] " F.L." " G.A." " H.I." " I.D." " I.L." " I.N." " I.A." " K.S." " K.Y."
[172] " L.A." " M.E." " M.T." " N.E." " N.V." " N.H." " N.J." " N.M." " N.Y."
[181] " N.C." " N.D." " O.H." " O.K." " O.R." " M.D." " M.A." " M.I." " M.N."
[190] " M.S." " M.O." " P.A." " R.I." " S.C." " S.D." " T.N." " T.X." " U.T."
[199] " V.T." " V.A." " W.A." " W.V." " W.I." " W.Y." " A.L"  " A.K"  " A.Z" 
[208] " A.R"  " C.A"  " C.O"  " C.T"  " D.E"  " D.C"  " F.L"  " G.A"  " H.I" 
[217] " I.D"  " I.L"  " I.N"  " I.A"  " K.S"  " K.Y"  " L.A"  " M.E"  " M.T" 
[226] " N.E"  " N.V"  " N.H"  " N.J"  " N.M"  " N.Y"  " N.C"  " N.D"  " O.H" 
[235] " O.K"  " O.R"  " M.D"  " M.A"  " M.I"  " M.N"  " M.S"  " M.O"  " P.A" 
[244] " R.I"  " S.C"  " S.D"  " T.N"  " T.X"  " U.T"  " V.T"  " V.A"  " W.A" 
[253] " W.V"  " W.I"  " W.Y"

In [72]:
print(sort(unique(df$test[grepl(paste(states, collapse = "|"), df$test)])))

 [1] " Abbeville SC, "                       
 [2] " Allegheny, P.A "                      
 [3] " Allegheny, PA. "                      
 [4] " Blacksburg, VA., "                    
 [5] " Bloomfield, NJ "                      
 [6] " Brooklyn NY, "                        
 [7] " Brooklyn, N.Y., "                     
 [8] " Charleston SC "                       
 [9] " Charleston SC., "                     
[10] " Charleston, SC, "                     
[11] " Cohoes, NY "                          
[12] " Copenhagen, NY "                      
[13] " Ellinwood, KS, U.S.A. "               
[14] " Elmira, NY "                          
[15] " Fairfield, N.Y. "                     
[16] " Lancaster, PA "                       
[17] " N York "                              
[18] " N,York "                              
[19] " N.J., USA "                           
[20] " N.Jersey, "                           
[21] " N.Y U.S.A, "                          
[22] " N.Y U.S.A. "               

In [73]:
docids <- 
df %>% 
filter(grepl(paste(states, collapse = "|"), test)) %>% 
filter(!grepl("McArdle|McEarlane|Indies", test)) %>% 
#select(docid, test)
#unique()
pull(docid)

In [74]:
df$authorLocation[df$docid %in% docids] <- "USA"
summary(df$authorLocation)

Canada    USA   NA's 
   310   1257   1204

In [75]:
cities <- c("Philadel", 
            "Chicag", 
            "New Orlean", 
            "Washin",  
            "San Francisco", 
            "Augusta", 
            "Petersburg",
            "Washin",
            "New Orleans",
            "San Francisco",
            "Baltimore",
            "Pittsburg",
            "Savannah",
            "Brooklyn",
            "Detroit",
            "Fresno",
            "Lynchburg",
            "Buffalo",
            "Cincinnat",
            "Sacrame",
            "Jeffersonville",
            "Pontiac",
            "Southfield",
            "Albany",
            "Cleveland",
            "Birmingham",
            "Frankford",
            "Grand Rapids",
            "Healdsburg",
            "Lynchburg",
            "Milwaukee",
            "N\\. York",
            "West Salem",
            "Wichita",
            "Abbeville",
            "Agnesville",
            "Allegheny",
            "Ansley",
            "Birmingham",
            "Blacksburg",
            "Boston",
            "Campbell\\'s Corner",
            "Chambersburg",
            "Charlevoix",
            "Cherokee City",
            "Concord",
            "Danielsonville",
            "Fairfield",
            "Fremont",
            "Greensburg",
            "Harvey",
            "Holly Hill",
            "Jackonsville",
            "Jersey City",
            "Kalamazoo",
            "Kalkaska",
            "Kaolin",
            "Kittanning",
            "Louisville",
            "Marshall",
            "Maryville",
            "Minneapolis",
            "Monticello",
            "N\\. Orleans",
            "N\\. York Cty",
            "N\\.Orleans",
            "Napa City",
            "New London, U\\.S\\.",
            "New Windsor",
            "Newburgh",
            "Newcastle De\\.",
            "Oakland",
            "Oxford\\, Mich",
            "Paterson")
cities  <- sort(cities)
cities

other <- c("Calif",
              "America",
              "Bucks County",
              "Mass\\.",
              "Charlotte County",
              "Mississipi",
              "Pa\\.",
              "Pennslyvania")
other <- sort(other)
other

[1] "Abbeville"            "Agnesville"           "Albany"              
 [4] "Allegheny"            "Ansley"               "Augusta"             
 [7] "Baltimore"            "Birmingham"           "Birmingham"          
[10] "Blacksburg"           "Boston"               "Brooklyn"            
[13] "Buffalo"              "Campbell\\'s Corner"  "Chambersburg"        
[16] "Charlevoix"           "Cherokee City"        "Chicag"              
[19] "Cincinnat"            "Cleveland"            "Concord"             
[22] "Danielsonville"       "Detroit"              "Fairfield"           
[25] "Frankford"            "Fremont"              "Fresno"              
[28] "Grand Rapids"         "Greensburg"           "Harvey"              
[31] "Healdsburg"           "Holly Hill"           "Jackonsville"        
[34] "Jeffersonville"       "Jersey City"          "Kalamazoo"           
[37] "Kalkaska"             "Kaolin"               "Kittanning"          
[40] "Louisville"           "Lynchburg"            "Lynchburg"           
[43] "Marshall"             "Maryville"            "Milwaukee"           
[46] "Minneapolis"          "Monticello"           "N\\. Orleans"        
[49] "N\\. York"            "N\\. York Cty"        "N\\.Orleans"         
[52] "Napa City"            "New London, U\\.S\\." "New Orlean"          
[55] "New Orleans"          "New Windsor"          "Newburgh"            
[58] "Newcastle De\\."      "Oakland"              "Oxford\\, Mich"      
[61] "Paterson"             "Petersburg"           "Philadel"            
[64] "Pittsburg"            "Pontiac"              "Sacrame"             
[67] "San Francisco"        "San Francisco"        "Savannah"            
[70] "Southfield"           "Washin"               "Washin"              
[73] "West Salem"           "Wichita"

[1] "America"          "Bucks County"     "Calif"            "Charlotte County"
[5] "Mass\\."          "Mississipi"       "Pa\\."            "Pennslyvania"

In [76]:
df$authorLocation[grepl(paste(other, collapse = "|"), df$test)] <- "USA"
summary(df$authorLocation)

Canada    USA   NA's 
   310   1292   1169

In [77]:
df$authorLocation[grepl(paste(cities, collapse = "|"), df$test)] <- "USA"
summary(df$authorLocation)

Canada    USA   NA's 
   310   1890    571

In [78]:
cities <- c("Philadephia",
            "Platsburgh",
            "Plymouth",
            "Rock Island",
            "Rockycreek",
            "Roxbury",
            "Saint Louis",
            "Sanfrancisco",
            "Springfield",
            "Spruce Creek",
            "Susquehanna",
            "Wolford",
            "Belvidere",
            "Ottawa.*Il\\."
           )
cities  <- sort(cities)
cities

other <- c("S\\. Carolina",
          "South of Carolina U\\.S\\.",
          "\\bVa\\b",
          "Waccamaw",
          "Chebanse",
          "Irish Channel")
other <- sort(other)
other

[1] "Belvidere"     "Ottawa.*Il\\." "Philadephia"   "Platsburgh"   
 [5] "Plymouth"      "Rock Island"   "Rockycreek"    "Roxbury"      
 [9] "Saint Louis"   "Sanfrancisco"  "Springfield"   "Spruce Creek" 
[13] "Susquehanna"   "Wolford"

[1] "\\bVa\\b"                   "Chebanse"                  
[3] "Irish Channel"              "S\\. Carolina"             
[5] "South of Carolina U\\.S\\." "Waccamaw"

In [79]:
df$authorLocation[grepl(paste(cities, collapse = "|"), df$test)] <- "USA"
df$authorLocation[grepl(paste(other, collapse = "|"), df$test)] <- "USA"
summary(df$authorLocation)

Canada    USA   NA's 
   310   1917    544

In [80]:
cities <- c("Milford",
            "Goderich",
            "Montreal",
            "Calgary",
            "Ottawa",
            "Halifax",
            "St.*John",
            "Temperanceville",
            "Amherst Island",
            "Bosanquet",
            "Coleraine",
            "Grosse Island",
            "Little Britain",
            "Indian Island",
            "Lawrenceville",
            "Marmora",
            "Owen Sound",
            "Point St Charles",
            "Smithville",
            "Wainfleet",
            "Watsonville",
            "Weldon",
            "Winnipeg",
            "Toronto",
            "Vancouver",
            "Edmonton"
           )
cities  <- sort(cities)
cities

other <- c("Cumberland Co")
other <- sort(other)
other

[1] "Amherst Island"   "Bosanquet"        "Calgary"          "Coleraine"       
 [5] "Edmonton"         "Goderich"         "Grosse Island"    "Halifax"         
 [9] "Indian Island"    "Lawrenceville"    "Little Britain"   "Marmora"         
[13] "Milford"          "Montreal"         "Ottawa"           "Owen Sound"      
[17] "Point St Charles" "Smithville"       "St.*John"         "Temperanceville" 
[21] "Toronto"          "Vancouver"        "Wainfleet"        "Watsonville"     
[25] "Weldon"           "Winnipeg"

[1] "Cumberland Co"

In [81]:
df$authorLocation[grepl(paste(other, collapse = "|"), df$test)] <- "Canada"
summary(df$authorLocation)

Canada    USA   NA's 
   311   1917    543

In [82]:
docids <- 
df %>% 
filter(grepl(paste(cities, collapse = "|"), test)) %>% 
filter(!grepl("Illinois|Il\\.", test)) %>% 
#select(docid, test)
pull(docid)

In [83]:
#sort(df$test[grepl(paste(cities, collapse = "|"), df$test)])

In [84]:
df$authorLocation[df$docid %in% docids] <- "Canada"
summary(df$authorLocation)

Canada    USA   NA's 
   423   1917    431

In [85]:
df %>% 
filter(is.na(authorLocation)) %>% 
select(docid, test, description) %>% 
#pull(description) %>% 
unique() #%>% 
#print()

docid
1   20514
2   20538
3   20724
4   20937
5   20950
6   21003
7   21043
8   21070
9   21145
10  21171
11  21189
12  21306
13  21319
14  21324
15  21581
16  21590
17  21631
18  21644
19  21766
20  21883
21  21887
22  22232
23  22325
24  22499
25  22630
26  22738
27  22795
28  23091
29  23103
30  23155
⋮   ⋮    
402 51237
403 51246
404 51247
405 51301
406 51343
407 51496
408 51942
409 51998
410 52069
411 52177
412 52179
413 52219
414 52316
415 52450
416 52460
417 52472
418 52680
419 52960
420 52980
421 53017
422 53065
423 53183
424 53212
425 53241
426 53293
427 53460
428 53527
429 53566
430 53624
431 53653
    test                                                                                    
1    Desertmartin                                                                           
2    Near Panama,                                                                           
3    ,                                                                                      
4    Brighton                                                                               
5   John Parks                                                                              
6   Thomas Armstrong                                                                        
7   Reference written by James Barbour for Henry Johnson.;                                  
8    Watertown                                                                              
9    Holly                                                                                  
10  letter from Eliza Steele                                                                
11                                                                                          
12  R.A. Taylor                                                                             
13                                                                                          
14                                                                                          
15   Hamilton,                                                                              
16   Coracrow,                                                                              
17   Law Offices, N.O.                                                                      
18   Antrim,                                                                                
19  Jane Chambers & Alexander Park toDear Brothers & Sisters;Dermot Lyttle; CMSIED 201001015
20   Fort Cornwallis                                                                        
21   Georgetown                                                                             
22   Garryduff,                                                                             
23   Dublin,                                                                                
24   Belfast,                                                                               
25  Alexander Patterson                                                                     
26   Ballybofey                                                                             
27   Antrim,                                                                                
28  H.Y. Hamilton Young                                                                     
29   ,                                                                                      
30   Kesh,                                                                                  
⋮   ⋮                                                                                       
402  Barrytown                                                                              
403  Beekskeell,                                                                            
404  New Young,                                                                             
405  Ederney                                                                                
406  Ednaclegh Edenclogh,           

In [86]:
docids <- c("21319", "21324", "52472", "53460", "53624")
df$authorLocation[df$docid %in% docids] <- "USA"
summary(df$authorLocation)

Canada    USA   NA's 
   423   1922    426

In [87]:
df <- df[!is.na(df$authorLocation),]

In [88]:
dfPlaces <- df

## Mapping names to genders

In [89]:
#re-set
df <- dfPlaces

In [90]:
df$authorgender <- NA
summary(as.factor(df$authorgender))

NA's 
2345

In [91]:
namesB <- intersect(namesFemale, namesMale)
namesB <- namesB$V1
length(namesB)

[1] 365

In [92]:
namesF <- setdiff(namesFemale, namesMale)
namesF <- as.vector(namesF$V1)
length(namesF)

namesM <- setdiff(namesMale,namesFemale)
namesM <- as.vector(namesM$V1)
length(namesM)

[1] 4633

[1] 2578

In [93]:
names <- union(namesFemale, namesMale)
names <- names$V1
length(names)

# Check
length(namesB)+length(namesF)+length(namesM)

[1] 7576

[1] 7576

In [94]:
# Because of memory limitations, I have to break this process into chunks of 1000 names
# When letters are co-authored by male and females, they are coded as "F" to indicate that a women participated in the writing.

namesF <- setdiff(namesFemale, namesMale)
namesF <- as.vector(namesF$V1[0:1000])
length(namesF)
namesF[0:10]

namesM <- setdiff(namesMale,namesFemale)
namesM <- as.vector(namesM$V1[0:1000])
length(namesM)
namesM[0:10]

df$authorgender[grepl(paste(namesM, collapse = "|"), df$docauthorname)] <- "M"
df$authorgender[grepl(paste(namesF, collapse = "|"), df$docauthorname)] <- "F"
summary(as.factor(df$authorgender))

[1] 1000

[1] "Abagael" "Abagail" "Abbe"    "Abbi"    "Abigael" "Abigail" "Abigale"
 [8] "Abra"    "Acacia"  "Ada"

[1] 1000

[1] "Aamir"      "Aaron"      "Abbot"      "Abbott"     "Abdel"     
 [6] "Abdul"      "Abdulkarim" "Abdullah"   "Abe"        "Abel"

F    M NA's 
 215  536 1594

In [95]:
# Because of memory limitations, I have to break this process into chunks of 1000 names

namesF <- setdiff(namesFemale, namesMale)
namesF <- as.vector(namesF$V1[1001:2000])
length(namesF)
namesF[0:10]

namesM <- setdiff(namesMale,namesFemale)
namesM <- as.vector(namesM$V1[1001:2000])
length(namesM)
namesM[0:10]

df$authorgender[grepl(paste(namesM, collapse = "|"), df$docauthorname)] <- "M"
df$authorgender[grepl(paste(namesF, collapse = "|"), df$docauthorname)] <- "F"
summary(as.factor(df$authorgender))

[1] 1000

[1] "Corabella" "Corabelle" "Coral"     "Coralie"   "Coraline"  "Coralyn"  
 [7] "Cordelia"  "Cordelie"  "Cordey"    "Cordie"

[1] 1000

[1] "Hermon"   "Hermy"    "Hernando" "Herold"   "Herrick"  "Herrmann"
 [7] "Hersch"   "Herschel" "Hersh"    "Hershel"

F    M NA's 
 271 1307  767

In [96]:
# Because of memory limitations, I have to break this process into chunks of 1000 names

namesF <- setdiff(namesFemale, namesMale)
namesF <- as.vector(namesF$V1[2001:3000])
length(namesF)
namesF[0:10]

namesM <- setdiff(namesMale,namesFemale)
namesM <- as.vector(namesM$V1[2001:2578])
length(namesM)
namesM[0:10]

df$authorgender[grepl(paste(namesM, collapse = "|"), df$docauthorname)] <- "M"
df$authorgender[grepl(paste(namesF, collapse = "|"), df$docauthorname)] <- "F"
summary(as.factor(df$authorgender))

[1] 1000

[1] "Hertha"    "Hester"    "Hesther"   "Hestia"    "Hetti"     "Hettie"   
 [7] "Hetty"     "Hilarie"   "Hilda"     "Hildagard"

[1] 578

[1] "Selby"    "Selig"    "Serge"    "Sergeant" "Sergei"   "Sergent" 
 [7] "Sergio"   "Seth"     "Seymour"  "Shadow"

F    M NA's 
 403 1445  497

In [97]:
# Because of memory limitations, I have to break this process into chunks of 1000 names
# Only running female code because male names have been exhausted.

namesF <- setdiff(namesFemale, namesMale)
namesF <- as.vector(namesF$V1[3001:4000])
length(namesF)
namesF[0:10]

df$authorgender[grepl(paste(namesF, collapse = "|"), df$docauthorname)] <- "F"
summary(as.factor(df$authorgender))

[1] 1000

[1] "Maire"   "Mairead" "Maisey"  "Maisie"  "Mala"    "Malanie" "Malcah" 
 [8] "Malena"  "Malia"   "Malina"

F    M NA's 
 577 1345  423

In [98]:
# Because of memory limitations, I have to break this process into chunks of 1000 names
# Only running female code because male names have been exhausted.

namesF <- setdiff(namesFemale, namesMale)
namesF <- as.vector(namesF$V1[4001:4633])
length(namesF)
namesF[0:10]

df$authorgender[grepl(paste(namesF, collapse = "|"), df$docauthorname)] <- "F"
summary(as.factor(df$authorgender))

[1] 633

[1] "Sarajane" "Saree"    "Sarena"   "Sarene"   "Sarette"  "Sari"    
 [7] "Sarina"   "Sarine"   "Sarita"   "Sashenka"

F    M NA's 
 581 1342  422

What are the names for the NAs?

In [99]:
sort(unique(df$docauthorname[is.na(df$authorgender)]))

[1] "A & L Greenlees"    "A McFeeters"        "A. Aitken"         
  [4] "A. B. Mc Millan"    "A. Campbell"        "A. D. Cruickshank" 
  [7] "A. Greenlees"       "A. M."              "A. Mapherson"      
 [10] "A. McFeeters"       "A. W. Smyth"        "Anonymous"         
 [13] "Atrhur Quinn"       "Banks F"            "Banks R"           
 [16] "Bo"                 "C. A. Hutchinson"   "C. A. McFarland"   
 [19] "C. Hobson"          "C. Hutchinson"      "Caledon"           
 [22] "Carse"              "Charle"             "Charly"            
 [25] "D. N. Morgan"       "Doherty"            "Dufferin"          
 [28] "E. Brown"           "E. Cochrane"        "E. E. Griggs"      
 [31] "E. G. Kelly"        "E. I."              "E. O. Leech"       
 [34] "E. Savage"          "E. W. Farnham"      "F"                 
 [37] "Francis Atkinson"   "Frank"              "Fred Harwood"      
 [40] "G B Cumming"        "G."                 "G. B. Bosworth"    
 [43] "G. B. Cumming"      "Gamble Cra"         "Gorge Leycock"     
 [46] "H. C. Bryson"       "H. N. Rucker"       "H. Riddle"         
 [49] "H. Young"           "Harper C. Bryson"   "Hitchens"          
 [52] "I Weir"             "I. Pembe"           "I. Weir"           
 [55] "J & C McLees"       "J and A Re"         "J Banks Bloomfield"
 [58] "J Chambers"         "J Means"            "J."                
 [61] "J. Banks"           "J. Brown"           "J. Campbell"       
 [64] "J. Carrothers"      "J. Chambers"        "J. Cochrane"       
 [67] "J. Gamble"          "J. Horner"          "J. J. Bowen"       
 [70] "J. J. Elder"        "J. M. Orr"          "J. McClellan"      
 [73] "J. Moon"            "J. Mullawney"       "J. Mulligan"       
 [76] "J. N. Hou"          "J. R. Savage"       "J. S."             
 [79] "J. Stinson"         "J. T. Mahoney"      "J. Wightman"       
 [82] "J.& A R"            "L. N. Southworth"   "L. W. Kelley"      
 [85] "Lytle Black"        "M E"                "M McAuley"         
 [88] "M. A. Beggs"        "M. Brooks"          "M. Carrothers"     
 [91] "M. Dowsley"         "M. Driscoll"        "M. E. Ling"        
 [94] "M. Feeny"           "M. Gamble"          "M. McAuley"        
 [97] "M. Savage"          "McGowan"            "McIntyre"          
[100] "Miss Small"         "Mrs D Kerr"         "Mrs J. Young"      
[103] "Mrs M. Shanks"      "Mrs S."             "Mrs. M. Mulcahy"   
[106] "N. A. Hi"           "N. B. Smyth"        "N. Carrothers"     
[109] "N. J. Weir"         "N. P. Kellogg"      "N. Shanks"         
[112] "O Bouligny"         "O. Bouligny"        "O. R. Potter"      
[115] "Own Boyle"          "P. Brogan"          "P. Doherty"        
[118] "P. Vankuren"        "Patt M'Gowan"       "R & J. Smyth"      
[121] "R Campbell"         "R. Campbell"        "R. Given"          
[124] "R. Givin"           "R. Greaves"         "R. H. Kelly"       
[127] "R. J Waddell"       "R. J."              "R. J. Waddell"     
[130] "R. Patterson"       "R. Waddell"         "S. Dempster"       
[133] "S. McClure"         "S. S. Page"         "S. Wylly"          
[136] "Samual Mo"          "T. Bouchier"        "T. Hay"            
[139] "T. Hou"             "T. McCoy"           "T. W. Coskery"     
[142] "Theophilus Potts"   "Thos. W. Coskery"   "Thos. Warnock"     
[145] "W K Harshaw"        "W McClurg"          "W Stavely"         
[148] "W. A. Clubley"      "W. D. Holmes"       "W. G. Weir"        
[151] "W. H. Downes"       "W. H. Gove"         "W. H. McCleery"    
[154] "W. Hinshaw"         "W. J. Muir"         "W. J. Stavely"     
[157] "W. J. Weir"         "W. K. Harshaw"      "W. McSparron"      
[160] "W. Morgan Gurley"   "W. New Orleans"     "W. Rolation"       
[163] "W. Stavely"         "W. Weir"            "Wilmin"            
[166] "Wm G. Weir"         "Wm. McCleery"       "Wm. McElderry"     
[169] "Wm. McFarland"      "Wm. McSparron"      "Wm. Shanks"        
[172] "Wm. Weir"           "Wm. Young"

In [100]:
# Making a few corrections
vals <- c("Atrhur", "Charly", "Frank", "Fred", "Wm\\.", "Gorge", "Samual", "Theophilus", "Thos\\.")
df$authorgender[grepl(paste(vals, collapse = "|"), df$docauthorname)] <- "M"

vals <- c("Mrs","Miss")
df$authorgender[grepl(paste(vals, collapse = "|"), df$docauthorname)] <- "F"

#Summary
summary(as.factor(df$authorgender))

F    M NA's 
 597 1365  383

## Summary Statistics

In [101]:
df <- factorize(df)

In [102]:
glimpse(df)

Rows: 2,345
Columns: 21
$ idIED          <int> 300090, 9501251, 9408355, 9003061, 9011027, 9905110, 94…
$ ddmmyyyy       <fct> 04-12-1896, 12-01-1891, 01-10-1842, 10-01-1896, 13-02-1…
$ publisher      <fct> IED, IED, IED, IED, IED, IED, IED, IED, IED, IED, IED, …
$ sourcetitle    <fct> "Public Record Office, Northern Ireland", "Public Recor…
$ description    <fct> "Edward Stanley, Katawa, Canada to Joshua Peel, Armagh;…
$ docid          <int> 20481, 20487, 20519, 20522, 20529, 20530, 20563, 20568,…
$ nationalOrigin <fct> Irish, Irish, Irish, Irish, Irish, Irish, Irish, Irish,…
$ authorgender   <fct> M, NA, F, F, M, M, NA, M, F, M, NA, NA, F, F, M, F, M, …
$ agewriting     <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ agedeath       <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ relMin         <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ U              <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ M             

In [103]:
vars <- c("docid", "nationalOrigin", "authorgender", "relMin", "U", "M", "S", "F", "L", "docmonth", "docyear", "docauthorname", "authorLocation")
df <- df[vars]
summary(df)

     docid       nationalOrigin authorgender  relMin           U          
 Min.   :20481   Irish:2345     F   : 597    Mode:logical   Mode:logical  
 1st Qu.:28328                  M   :1365    NA's:2345      NA's:2345     
 Median :36427                  NA's: 383                                 
 Mean   :36636                                                            
 3rd Qu.:44933                                                            
 Max.   :53643                                                            
                                                                          
    M              S              F              L              docmonth   
 Mode:logical   Mode:logical   Mode:logical   Mode:logical   01     : 283  
 NA's:2345      NA's:2345      NA's:2345      NA's:2345      12     : 233  
                                                             06     : 209  
                                                             11     : 209  
                    

In [104]:
length(unique(df$docauthorname))

[1] 1063

## Make Unique Identifiers

In [105]:
# Make unique identifiers for all
df01 <- df %>%
 group_by(docauthorname) %>%
 mutate(docauthorid = cur_group_id())

In [106]:
summary(df01)

     docid       nationalOrigin authorgender  relMin           U          
 Min.   :20481   Irish:2345     F   : 597    Mode:logical   Mode:logical  
 1st Qu.:28328                  M   :1365    NA's:2345      NA's:2345     
 Median :36427                  NA's: 383                                 
 Mean   :36636                                                            
 3rd Qu.:44933                                                            
 Max.   :53643                                                            
                                                                          
    M              S              F              L              docmonth   
 Mode:logical   Mode:logical   Mode:logical   Mode:logical   01     : 283  
 NA's:2345      NA's:2345      NA's:2345      NA's:2345      12     : 233  
                                                             06     : 209  
                                                             11     : 209  
                    

In [107]:
df01$docauthorid[0:50]
df01$docauthorid <- sprintf("%004d", df01$docauthorid)
df01$docauthorid[0:50]

[1]  196   89   48  253 1028  239  728  432  198  810  744   89  649  408  789
[16]  578   15  663  192  410  880 1032  431    6  459  763  871 1035 1053 1027
[31]   40  319 1037  306 1022  410   89  273  387  273  179  249  169  257  912
[46]  289   36   55  880  310

[1] "0196" "0089" "0048" "0253" "1028" "0239" "0728" "0432" "0198" "0810"
[11] "0744" "0089" "0649" "0408" "0789" "0578" "0015" "0663" "0192" "0410"
[21] "0880" "1032" "0431" "0006" "0459" "0763" "0871" "1035" "1053" "1027"
[31] "0040" "0319" "1037" "0306" "1022" "0410" "0089" "0273" "0387" "0273"
[41] "0179" "0249" "0169" "0257" "0912" "0289" "0036" "0055" "0880" "0310"

In [108]:
df01$docauthorid[0:50]
df01$docauthorid <- gsub("^", "IED", df01$docauthorid)
df01$docauthorid[0:50]

[1] "0196" "0089" "0048" "0253" "1028" "0239" "0728" "0432" "0198" "0810"
[11] "0744" "0089" "0649" "0408" "0789" "0578" "0015" "0663" "0192" "0410"
[21] "0880" "1032" "0431" "0006" "0459" "0763" "0871" "1035" "1053" "1027"
[31] "0040" "0319" "1037" "0306" "1022" "0410" "0089" "0273" "0387" "0273"
[41] "0179" "0249" "0169" "0257" "0912" "0289" "0036" "0055" "0880" "0310"

[1] "IED0196" "IED0089" "IED0048" "IED0253" "IED1028" "IED0239" "IED0728"
 [8] "IED0432" "IED0198" "IED0810" "IED0744" "IED0089" "IED0649" "IED0408"
[15] "IED0789" "IED0578" "IED0015" "IED0663" "IED0192" "IED0410" "IED0880"
[22] "IED1032" "IED0431" "IED0006" "IED0459" "IED0763" "IED0871" "IED1035"
[29] "IED1053" "IED1027" "IED0040" "IED0319" "IED1037" "IED0306" "IED1022"
[36] "IED0410" "IED0089" "IED0273" "IED0387" "IED0273" "IED0179" "IED0249"
[43] "IED0169" "IED0257" "IED0912" "IED0289" "IED0036" "IED0055" "IED0880"
[50] "IED0310"

In [109]:
vals <- make.unique(df01$docauthorid[df01$docauthorid=="IED0089"])
vals

[1] "IED0089"    "IED0089.1"  "IED0089.2"  "IED0089.3"  "IED0089.4" 
 [6] "IED0089.5"  "IED0089.6"  "IED0089.7"  "IED0089.8"  "IED0089.9" 
[11] "IED0089.10" "IED0089.11" "IED0089.12" "IED0089.13" "IED0089.14"
[16] "IED0089.15" "IED0089.16" "IED0089.17" "IED0089.18" "IED0089.19"
[21] "IED0089.20" "IED0089.21" "IED0089.22" "IED0089.23" "IED0089.24"
[26] "IED0089.25" "IED0089.26" "IED0089.27" "IED0089.28" "IED0089.29"
[31] "IED0089.30" "IED0089.31" "IED0089.32" "IED0089.33" "IED0089.34"
[36] "IED0089.35" "IED0089.36" "IED0089.37" "IED0089.38" "IED0089.39"
[41] "IED0089.40" "IED0089.41" "IED0089.42" "IED0089.43" "IED0089.44"
[46] "IED0089.45" "IED0089.46" "IED0089.47" "IED0089.48" "IED0089.49"
[51] "IED0089.50" "IED0089.51" "IED0089.52" "IED0089.53" "IED0089.54"
[56] "IED0089.55" "IED0089.56" "IED0089.57" "IED0089.58" "IED0089.59"
[61] "IED0089.60" "IED0089.61" "IED0089.62" "IED0089.63" "IED0089.64"
[66] "IED0089.65" "IED0089.66" "IED0089.67" "IED0089.68" "IED0089.69"
[71] "IED0089.70" "IED0089.71" "IED0089.72" "IED0089.73" "IED0089.74"
[76] "IED0089.75" "IED0089.76" "IED0089.77" "IED0089.78" "IED0089.79"
[81] "IED0089.80" "IED0089.81" "IED0089.82" "IED0089.83" "IED0089.84"
[86] "IED0089.85" "IED0089.86" "IED0089.87" "IED0089.88" "IED0089.89"
[91] "IED0089.90" "IED0089.91" "IED0089.92" "IED0089.93" "IED0089.94"
[96] "IED0089.95" "IED0089.96"

In [110]:
df01$docauthorid[df01$docauthorid=="IED0089"] <- vals
df01$docauthorname[grepl("IED0089", df01$docauthorid)] 

[1] Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous
 [8] Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous
[15] Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous
[22] Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous
[29] Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous
[36] Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous
[43] Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous
[50] Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous
[57] Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous
[64] Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous
[71] Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous
[78] Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous
[85] Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous
[92] Anonymous Anonymous Anonymous Anonymous Anonymous Anonymous
1063 Levels: A & L Greenlees A McFeeters A S Woodburn ... Wm. Young

In [111]:
df01 <- factorize(df01)
summary(df01)

     docid       nationalOrigin authorgender  relMin           U          
 Min.   :20481   Irish:2345     F   : 597    Mode:logical   Mode:logical  
 1st Qu.:28328                  M   :1365    NA's:2345      NA's:2345     
 Median :36427                  NA's: 383                                 
 Mean   :36636                                                            
 3rd Qu.:44933                                                            
 Max.   :53643                                                            
                                                                          
    M              S              F              L              docmonth   
 Mode:logical   Mode:logical   Mode:logical   Mode:logical   01     : 283  
 NA's:2345      NA's:2345      NA's:2345      NA's:2345      12     : 233  
                                                             06     : 209  
                                                             11     : 209  
                    

## Save subset

In [112]:
write.csv(df01, 
          "20240502_PhD_IEDSubset.csv", 
          row.names=FALSE)

In [113]:
glimpse(df01)

Rows: 2,345
Columns: 14
Groups: docauthorname [1,063]
$ docid          <int> 20481, 20487, 20519, 20522, 20529, 20530, 20563, 20568,…
$ nationalOrigin <fct> Irish, Irish, Irish, Irish, Irish, Irish, Irish, Irish,…
$ authorgender   <fct> M, NA, F, F, M, M, NA, M, F, M, NA, NA, F, F, M, F, M, …
$ relMin         <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ U              <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ M              <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ S              <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ F              <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ L              <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ docmonth       <fct> 12, 01, 10, 01, 02, 05, 02, 09, 03, 01, 08, 09, 03, 07,…
$ docyear        <dbl> 1896, 1891, 1842, 1896, 1873, 1891, 1858, 1886, 1808, 1…
$ docauthorname  <fct> Edward Stanley, Anonymous, Alexander McCloy